## Library import

In [32]:
import pandas as pd
import dask.dataframe as dd

import numpy as np
import geopandas as gpd
import scipy
import shapely
import matplotlib.pyplot as plt

In [2]:
pd.set_option('display.max_columns', 35)

## Data import

In [3]:
df = dd.read_csv('./data/EMS_Incident_Dispatch_Data.csv')

In [33]:
gdf = gpd.read_file('../CAPSTONE/zipcodes/ZIP_CODE_040114.shp')

In [4]:
df.tail()

,CAD_INCIDENT_ID,INCIDENT_DATETIME,INITIAL_CALL_TYPE,INITIAL_SEVERITY_LEVEL_CODE,FINAL_CALL_TYPE,FINAL_SEVERITY_LEVEL_CODE,FIRST_ASSIGNMENT_DATETIME,VALID_DISPATCH_RSPNS_TIME_INDC,DISPATCH_RESPONSE_SECONDS_QY,FIRST_ACTIVATION_DATETIME,FIRST_ON_SCENE_DATETIME,VALID_INCIDENT_RSPNS_TIME_INDC,INCIDENT_RESPONSE_SECONDS_QY,INCIDENT_TRAVEL_TM_SECONDS_QY,FIRST_TO_HOSP_DATETIME,FIRST_HOSP_ARRIVAL_DATETIME,INCIDENT_CLOSE_DATETIME,HELD_INDICATOR,INCIDENT_DISPOSITION_CODE,BOROUGH,INCIDENT_DISPATCH_AREA,ZIPCODE,POLICEPRECINCT,CITYCOUNCILDISTRICT,COMMUNITYDISTRICT,COMMUNITYSCHOOLDISTRICT,CONGRESSIONALDISTRICT,REOPEN_INDICATOR,SPECIAL_EVENT_INDICATOR,STANDBY_INDICATOR,TRANSFER_INDICATOR
52479,130010006,01/01/2013 12:01:26 AM,INJURY,5,INJURY,5,01/01/2013 12:01:58 AM,Y,32,01/01/2013 12:02:55 AM,01/01/2013 12:15:42 AM,Y,856.0,824.0,01/01/2013 12:27:42 AM,01/01/2013 12:31:13 AM,01/01/2013 12:53:12 AM,N,82.0,BRONX,B2,10457.0,48.0,15.0,206.0,10.0,15.0,N,N,N,N
52480,130010005,01/01/2013 12:01:16 AM,SICK,6,SICK,6,01/01/2013 12:02:12 AM,Y,56,01/01/2013 12:02:55 AM,01/01/2013 12:15:04 AM,Y,828.0,772.0,01/01/2013 12:34:54 AM,01/01/2013 12:53:02 AM,01/01/2013 01:20:28 AM,N,82.0,BRONX,B2,10453.0,46.0,14.0,205.0,10.0,15.0,N,N,N,N
52481,130010004,01/01/2013 12:01:04 AM,ARREST,1,ARREST,1,01/01/2013 12:01:33 AM,Y,29,01/01/2013 12:01:58 AM,01/01/2013 12:08:13 AM,Y,429.0,400.0,NaN,NaN,01/01/2013 12:38:05 AM,N,83.0,QUEENS,Q3,11418.0,102.0,29.0,409.0,27.0,5.0,N,N,N,N
52482,130010002,01/01/2013 12:00:19 AM,CARD,3,CARD,3,01/01/2013 12:01:18 AM,Y,59,01/01/2013 12:02:08 AM,01/01/2013 12:14:30 AM,Y,851.0,792.0,NaN,NaN,01/01/2013 12:55:34 AM,N,93.0,BRONX,B1,10454.0,40.0,8.0,201.0,7.0,15.0,N,N,N,N
52483,130010001,01/01/2013 12:00:04 AM,RESPIR,4,RESPIR,4,01/01/2013 12:01:45 AM,Y,101,01/01/2013 12:01:51 AM,01/01/2013 12:13:21 AM,Y,797.0,696.0,01/01/2013 12:28:49 AM,01/01/2013 12:38:15 AM,01/01/2013 01:04:56 AM,N,82.0,BRONX,B3,10472.0,43.0,18.0,209.0,12.0,15.0,N,N,N,N

In [8]:
# resulting df is same size as original df, no duplicates found
df.drop_duplicates().compute()

,CAD_INCIDENT_ID,INCIDENT_DATETIME,INITIAL_CALL_TYPE,INITIAL_SEVERITY_LEVEL_CODE,FINAL_CALL_TYPE,FINAL_SEVERITY_LEVEL_CODE,FIRST_ASSIGNMENT_DATETIME,VALID_DISPATCH_RSPNS_TIME_INDC,DISPATCH_RESPONSE_SECONDS_QY,FIRST_ACTIVATION_DATETIME,FIRST_ON_SCENE_DATETIME,VALID_INCIDENT_RSPNS_TIME_INDC,INCIDENT_RESPONSE_SECONDS_QY,INCIDENT_TRAVEL_TM_SECONDS_QY,FIRST_TO_HOSP_DATETIME,FIRST_HOSP_ARRIVAL_DATETIME,INCIDENT_CLOSE_DATETIME,HELD_INDICATOR,INCIDENT_DISPOSITION_CODE,BOROUGH,INCIDENT_DISPATCH_AREA,ZIPCODE,POLICEPRECINCT,CITYCOUNCILDISTRICT,COMMUNITYDISTRICT,COMMUNITYSCHOOLDISTRICT,CONGRESSIONALDISTRICT,REOPEN_INDICATOR,SPECIAL_EVENT_INDICATOR,STANDBY_INDICATOR,TRANSFER_INDICATOR
0,183654386,12/31/2018 11:59:46 PM,CARDBR,2,CARDBR,2,12/31/2018 11:59:54 PM,Y,8,01/01/2019 12:00:51 AM,01/01/2019 12:07:27 AM,Y,461.0,453.0,01/01/2019 12:15:08 AM,01/01/2019 12:21:51 AM,01/01/2019 01:00:20 AM,N,82.0,BROOKLYN,K6,11201.0,84.0,35.0,302.0,13.0,8.0,N,N,N,N
1,183654385,12/31/2018 11:59:20 PM,MVAINJ,4,MVAINJ,4,01/01/2019 12:01:10 AM,Y,110,01/01/2019 12:02:25 AM,01/01/2019 12:07:19 AM,Y,479.0,369.0,NaN,NaN,01/01/2019 12:19:49 AM,N,91.0,QUEENS,Q3,11416.0,102.0,32.0,409.0,27.0,7.0,N,N,N,N
2,183654384,12/31/2018 11:58:45 PM,SICK,6,SICK,6,01/01/2019 12:00:43 AM,Y,118,01/01/2019 12:02:08 AM,01/01/2019 12:14:18 AM,Y,933.0,815.0,01/01/2019 12:23:59 AM,01/01/2019 12:34:07 AM,01/01/2019 01:21:30 AM,N,82.0,QUEENS,Q6,11369.0,115.0,21.0,480.0,30.0,14.0,N,N,N,N
3,183654383,12/31/2018 11:58:14 PM,INJMAJ,3,INJMAJ,3,12/31/2018 11:58:22 PM,Y,8,12/31/2018 11:58:37 PM,01/01/2019 12:04:10 AM,Y,356.0,348.0,01/01/2019 01:06:29 AM,01/01/2019 01:15:30 AM,01/01/2019 02:02:12 AM,N,82.0,BROOKLYN,K1,11214.0,62.0,47.0,311.0,20.0,11.0,N,N,N,N
4,183654382,12/31/2018 11:57:42 PM,UNC,2,UNC,2,01/01/2019 12:00:39 AM,Y,177,01/01/2019 12:01:03 AM,01/01/2019 12:15:00 AM,Y,1038.0,861.0,01/01/2019 01:18:22 AM,01/01/2019 01:22:01 AM,01/01/2019 02:34:19 AM,N,82.0,MANHATTAN,M3,10019.0,18.0,4.0,105.0,2.0,12.0,N,N,N,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
52479,130010006,01/01/2013 12:01:26 AM,INJURY,5,INJURY,5,01/01/2013 12:01:58 AM,Y,32,01/01/2013 12:02:55 AM,01/01/2013 12:15:42 AM,Y,856.0,824.0,01/01/2013 12:27:42 AM,01/01/2013 12:31:13 AM,01/01/2013 12:53:12 AM,N,82.0,BRONX,B2,10457.0,48.0,15.0,206.0,10.0,15.0,N,N,N,N
52480,130010005,01/01/2013 12:01:16 AM,SICK,6,SICK,6,01/01/2013 12:02:12 AM,Y,56,01/01/2013 12:02:55 AM,01/01/2013 12:15:04 AM,Y,828.0,772.0,01/01/2013 12:34:54 AM,01/01/2013 12:53:02 AM,01/01/2013 01:20:28 AM,N,82.0,BRONX,B2,10453.0,46.0,14.0,205.0,10.0,15.0,N,N,N,N
52481,130010004,01/01/2013 12:01:04 AM,ARREST,1,ARREST,1,01/01/2013 12:01:33 AM,Y,29,01/01/2013 12:01:58 AM,01/01/2013 12:08:13 AM,Y,429.0,400.0,NaN,NaN,01/01/2013 12:38:05 AM,N,83.0,QUEENS,Q3,11418.0,102.0,29.0,409.0,27.0,5.0,N,N,N,N
52482,130010002,01/01/2013 12:00:19 AM,CARD,3,CARD,3,01/01/2013 12:01:18 AM,Y,59,01/01/2013 12:02:08 AM,01/01/2013 12:14:30 AM,Y,851.0,792.0,NaN,NaN,01/01/2013 12:55:34 AM,N,93.0,BRONX,B1,10454.0,40.0,8.0,201.0,7.0,15.0,N,N,N,N
52483,130010001,01/01/2013 12:00:04 AM,RESPIR,4,RESPIR,4,01/01/2013 12:01:45 AM,Y,101,01/01/2013 12:01:51 AM,01/01/2013 12:13:21 AM,Y,797.0,696.0,01/01/2013 12:28:49 AM,01/01/2013 12:38:15 AM,01/01/2013 01:04:56 AM,N,82.0,BRONX,B3,10472.0,43.0,18.0,209.0,12.0,15.0,N,N,N,N

In [5]:
df.compute()

,CAD_INCIDENT_ID,INCIDENT_DATETIME,INITIAL_CALL_TYPE,INITIAL_SEVERITY_LEVEL_CODE,FINAL_CALL_TYPE,FINAL_SEVERITY_LEVEL_CODE,FIRST_ASSIGNMENT_DATETIME,VALID_DISPATCH_RSPNS_TIME_INDC,DISPATCH_RESPONSE_SECONDS_QY,FIRST_ACTIVATION_DATETIME,FIRST_ON_SCENE_DATETIME,VALID_INCIDENT_RSPNS_TIME_INDC,INCIDENT_RESPONSE_SECONDS_QY,INCIDENT_TRAVEL_TM_SECONDS_QY,FIRST_TO_HOSP_DATETIME,FIRST_HOSP_ARRIVAL_DATETIME,INCIDENT_CLOSE_DATETIME,HELD_INDICATOR,INCIDENT_DISPOSITION_CODE,BOROUGH,INCIDENT_DISPATCH_AREA,ZIPCODE,POLICEPRECINCT,CITYCOUNCILDISTRICT,COMMUNITYDISTRICT,COMMUNITYSCHOOLDISTRICT,CONGRESSIONALDISTRICT,REOPEN_INDICATOR,SPECIAL_EVENT_INDICATOR,STANDBY_INDICATOR,TRANSFER_INDICATOR
0,183654386,12/31/2018 11:59:46 PM,CARDBR,2,CARDBR,2,12/31/2018 11:59:54 PM,Y,8,01/01/2019 12:00:51 AM,01/01/2019 12:07:27 AM,Y,461.0,453.0,01/01/2019 12:15:08 AM,01/01/2019 12:21:51 AM,01/01/2019 01:00:20 AM,N,82.0,BROOKLYN,K6,11201.0,84.0,35.0,302.0,13.0,8.0,N,N,N,N
1,183654385,12/31/2018 11:59:20 PM,MVAINJ,4,MVAINJ,4,01/01/2019 12:01:10 AM,Y,110,01/01/2019 12:02:25 AM,01/01/2019 12:07:19 AM,Y,479.0,369.0,NaN,NaN,01/01/2019 12:19:49 AM,N,91.0,QUEENS,Q3,11416.0,102.0,32.0,409.0,27.0,7.0,N,N,N,N
2,183654384,12/31/2018 11:58:45 PM,SICK,6,SICK,6,01/01/2019 12:00:43 AM,Y,118,01/01/2019 12:02:08 AM,01/01/2019 12:14:18 AM,Y,933.0,815.0,01/01/2019 12:23:59 AM,01/01/2019 12:34:07 AM,01/01/2019 01:21:30 AM,N,82.0,QUEENS,Q6,11369.0,115.0,21.0,480.0,30.0,14.0,N,N,N,N
3,183654383,12/31/2018 11:58:14 PM,INJMAJ,3,INJMAJ,3,12/31/2018 11:58:22 PM,Y,8,12/31/2018 11:58:37 PM,01/01/2019 12:04:10 AM,Y,356.0,348.0,01/01/2019 01:06:29 AM,01/01/2019 01:15:30 AM,01/01/2019 02:02:12 AM,N,82.0,BROOKLYN,K1,11214.0,62.0,47.0,311.0,20.0,11.0,N,N,N,N
4,183654382,12/31/2018 11:57:42 PM,UNC,2,UNC,2,01/01/2019 12:00:39 AM,Y,177,01/01/2019 12:01:03 AM,01/01/2019 12:15:00 AM,Y,1038.0,861.0,01/01/2019 01:18:22 AM,01/01/2019 01:22:01 AM,01/01/2019 02:34:19 AM,N,82.0,MANHATTAN,M3,10019.0,18.0,4.0,105.0,2.0,12.0,N,N,N,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
52479,130010006,01/01/2013 12:01:26 AM,INJURY,5,INJURY,5,01/01/2013 12:01:58 AM,Y,32,01/01/2013 12:02:55 AM,01/01/2013 12:15:42 AM,Y,856.0,824.0,01/01/2013 12:27:42 AM,01/01/2013 12:31:13 AM,01/01/2013 12:53:12 AM,N,82.0,BRONX,B2,10457.0,48.0,15.0,206.0,10.0,15.0,N,N,N,N
52480,130010005,01/01/2013 12:01:16 AM,SICK,6,SICK,6,01/01/2013 12:02:12 AM,Y,56,01/01/2013 12:02:55 AM,01/01/2013 12:15:04 AM,Y,828.0,772.0,01/01/2013 12:34:54 AM,01/01/2013 12:53:02 AM,01/01/2013 01:20:28 AM,N,82.0,BRONX,B2,10453.0,46.0,14.0,205.0,10.0,15.0,N,N,N,N
52481,130010004,01/01/2013 12:01:04 AM,ARREST,1,ARREST,1,01/01/2013 12:01:33 AM,Y,29,01/01/2013 12:01:58 AM,01/01/2013 12:08:13 AM,Y,429.0,400.0,NaN,NaN,01/01/2013 12:38:05 AM,N,83.0,QUEENS,Q3,11418.0,102.0,29.0,409.0,27.0,5.0,N,N,N,N
52482,130010002,01/01/2013 12:00:19 AM,CARD,3,CARD,3,01/01/2013 12:01:18 AM,Y,59,01/01/2013 12:02:08 AM,01/01/2013 12:14:30 AM,Y,851.0,792.0,NaN,NaN,01/01/2013 12:55:34 AM,N,93.0,BRONX,B1,10454.0,40.0,8.0,201.0,7.0,15.0,N,N,N,N
52483,130010001,01/01/2013 12:00:04 AM,RESPIR,4,RESPIR,4,01/01/2013 12:01:45 AM,Y,101,01/01/2013 12:01:51 AM,01/01/2013 12:13:21 AM,Y,797.0,696.0,01/01/2013 12:28:49 AM,01/01/2013 12:38:15 AM,01/01/2013 01:04:56 AM,N,82.0,BRONX,B3,10472.0,43.0,18.0,209.0,12.0,15.0,N,N,N,N

In [7]:
# Where does .describe() actually do something useful here/which numeric columns actually contain continous data?
df.describe().compute()

,CAD_INCIDENT_ID,INITIAL_SEVERITY_LEVEL_CODE,FINAL_SEVERITY_LEVEL_CODE,DISPATCH_RESPONSE_SECONDS_QY,INCIDENT_RESPONSE_SECONDS_QY,INCIDENT_TRAVEL_TM_SECONDS_QY,INCIDENT_DISPOSITION_CODE,ZIPCODE,POLICEPRECINCT,CITYCOUNCILDISTRICT,COMMUNITYDISTRICT,COMMUNITYSCHOOLDISTRICT,CONGRESSIONALDISTRICT
count,8.557848e+06,8.557848e+06,8.557848e+06,8.557848e+06,8.283276e+06,8.284535e+06,8.487996e+06,8.393452e+06,8.393762e+06,8.390614e+06,8.393756e+06,8.389424e+06,8.390614e+06
mean,1.576735e+08,4.277234e+00,4.171099e+00,9.126130e+01,5.640595e+02,4.744960e+02,8.473824e+01,1.073609e+04,6.159616e+01,2.303020e+01,2.610761e+02,1.471603e+01,1.063469e+01
std,1.706354e+07,1.691518e+00,1.701282e+00,5.324385e+02,6.698499e+02,3.726474e+02,4.558447e+00,5.496244e+02,3.409391e+01,1.498240e+01,1.178349e+02,9.594994e+00,3.336092e+00
min,1.300100e+08,1.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,8.200000e+01,8.300000e+01,1.000000e+00,1.000000e+00,1.010000e+02,1.000000e+00,3.000000e+00
25%,1.501509e+08,3.000000e+00,3.000000e+00,1.600000e+01,3.280000e+02,2.950000e+02,8.200000e+01,1.030400e+04,4.000000e+01,1.000000e+01,2.010000e+02,7.000000e+00,8.000000e+00
50%,1.701227e+08,5.000000e+00,4.000000e+00,2.700000e+01,4.680000e+02,4.280000e+02,8.200000e+01,1.047300e+04,6.200000e+01,2.100000e+01,3.020000e+02,1.400000e+01,1.100000e+01
75%,1.834902e+08,6.000000e+00,6.000000e+00,5.700000e+01,6.990000e+02,6.300000e+02,9.000000e+01,1.122600e+04,9.000000e+01,3.700000e+01,3.180000e+02,2.300000e+01,1.300000e+01
max,1.836544e+08,9.000000e+00,8.000000e+00,3.233200e+04,3.237700e+04,9.539000e+04,9.600000e+01,1.234500e+04,1.230000e+02,5.100000e+01,5.950000e+02,3.200000e+01,1.600000e+01

**Note:** Most of these numeric variables are _NOT_ continuous-
* CAD_INCIDENT_ID = unique ID for each dispatched incident
* INITIAL/FINAL_SEVERITY_LEVEL_CODE = categorical ranking of severity
* Time-variables = mostly continuous
* INCIDENT_DISPOSITION_CODE =

In [10]:
df.groupby('INCIDENT_DISPOSITION_CODE').mean().compute()

,CAD_INCIDENT_ID,INITIAL_SEVERITY_LEVEL_CODE,FINAL_SEVERITY_LEVEL_CODE,DISPATCH_RESPONSE_SECONDS_QY,INCIDENT_RESPONSE_SECONDS_QY,INCIDENT_TRAVEL_TM_SECONDS_QY,ZIPCODE,POLICEPRECINCT,CITYCOUNCILDISTRICT,COMMUNITYDISTRICT,COMMUNITYSCHOOLDISTRICT,CONGRESSIONALDISTRICT
INCIDENT_DISPOSITION_CODE,,,,,,,,,,,,
82.0,1.574981e+08,4.211062,4.094433,73.657820,540.484035,466.868686,10747.328383,62.392340,23.343400,263.660966,14.916679,10.627929
83.0,1.574779e+08,1.543490,1.247004,30.694798,336.687017,306.023545,10821.249078,68.490727,25.332592,286.452565,16.816770,10.176383
87.0,1.539286e+08,4.519001,4.426052,193.128791,703.040104,510.703580,10746.312499,61.524448,23.174964,261.901409,14.738466,10.328032
90.0,1.582946e+08,4.613199,4.539752,131.217250,635.069396,505.642640,10697.356831,59.022301,21.808548,252.001293,14.013083,10.688138
91.0,1.619979e+08,4.653206,4.575987,337.484423,808.025232,488.099582,10827.726319,68.991843,24.944326,287.684550,16.778780,10.239166
92.0,1.594170e+08,4.553571,4.517857,93.660714,617.568627,516.960784,10755.446429,66.214286,23.500000,275.375000,15.714286,10.285714
93.0,1.588346e+08,4.245094,4.176672,77.272408,540.835387,463.618494,10713.008404,59.879226,22.610034,256.085528,14.356958,10.673308
94.0,1.567447e+08,3.977168,3.849081,82.790207,536.641007,454.351135,10896.169441,71.431034,28.266875,300.923454,17.785661,9.456586
95.0,1.583343e+08,4.639163,4.567734,121.552956,628.980100,506.967662,10358.412639,31.023544,11.376704,174.112763,7.337051,8.477076
96.0,1.585123e+08,4.703357,4.613598,231.368663,823.400841,595.868486,10653.682465,55.569729,20.641433,239.543754,13.005813,10.854164

In [32]:
df['INCIDENT_DISPOSITION_CODE'].value_counts().compute()

82.0    6037089
93.0     970026
90.0     748772
96.0     299626
87.0     265585
91.0     100662
83.0      58404
94.0       6964
95.0        812
92.0         56
Name: INCIDENT_DISPOSITION_CODE, dtype: int64

In [33]:
df['INCIDENT_DISPOSITION_CODE'].value_counts().sum().compute()

8487996

In [31]:
# What are the unique values for INCIDENT_DISPOSITION_CODE?
df['INCIDENT_DISPOSITION_CODE'].unique().compute()

0     82.0
1     91.0
2     93.0
3     90.0
4     96.0
5      NaN
6     87.0
7     83.0
8     94.0
9     95.0
10    92.0
Name: INCIDENT_DISPOSITION_CODE, dtype: float64

In [35]:
# How many NaNs are there for the INCIDENT_DISPOSITION_CODE??? 69_852
df['INCIDENT_DISPOSITION_CODE'].isna().sum().compute()

69852

In [17]:
df.count().compute()

CAD_INCIDENT_ID                   8557848
INCIDENT_DATETIME                 8557848
INITIAL_CALL_TYPE                 8557848
INITIAL_SEVERITY_LEVEL_CODE       8557848
FINAL_CALL_TYPE                   8557848
FINAL_SEVERITY_LEVEL_CODE         8557848
FIRST_ASSIGNMENT_DATETIME         8498783
VALID_DISPATCH_RSPNS_TIME_INDC    8557848
DISPATCH_RESPONSE_SECONDS_QY      8557848
FIRST_ACTIVATION_DATETIME         8483588
FIRST_ON_SCENE_DATETIME           8284662
VALID_INCIDENT_RSPNS_TIME_INDC    8557848
INCIDENT_RESPONSE_SECONDS_QY      8283276
INCIDENT_TRAVEL_TM_SECONDS_QY     8284535
FIRST_TO_HOSP_DATETIME            6031607
FIRST_HOSP_ARRIVAL_DATETIME       5990574
INCIDENT_CLOSE_DATETIME           8554621
HELD_INDICATOR                    8557848
INCIDENT_DISPOSITION_CODE         8487996
BOROUGH                           8557848
INCIDENT_DISPATCH_AREA            8557848
ZIPCODE                           8393452
POLICEPRECINCT                    8393762
CITYCOUNCILDISTRICT               8390614
COMMUNITYDISTRICT                 8393756
COMMUNITYSCHOOLDISTRICT           8389424
CONGRESSIONALDISTRICT             8390614
REOPEN_INDICATOR                  8557848
SPECIAL_EVENT_INDICATOR           8557848
STANDBY_INDICATOR                 8557848
TRANSFER_INDICATOR                8557848
dtype: int64

In [18]:
df[(df['INCIDENT_DISPOSITION_CODE'] == 87)].compute()

,CAD_INCIDENT_ID,INCIDENT_DATETIME,INITIAL_CALL_TYPE,INITIAL_SEVERITY_LEVEL_CODE,FINAL_CALL_TYPE,FINAL_SEVERITY_LEVEL_CODE,FIRST_ASSIGNMENT_DATETIME,VALID_DISPATCH_RSPNS_TIME_INDC,DISPATCH_RESPONSE_SECONDS_QY,FIRST_ACTIVATION_DATETIME,FIRST_ON_SCENE_DATETIME,VALID_INCIDENT_RSPNS_TIME_INDC,INCIDENT_RESPONSE_SECONDS_QY,INCIDENT_TRAVEL_TM_SECONDS_QY,FIRST_TO_HOSP_DATETIME,FIRST_HOSP_ARRIVAL_DATETIME,INCIDENT_CLOSE_DATETIME,HELD_INDICATOR,INCIDENT_DISPOSITION_CODE,BOROUGH,INCIDENT_DISPATCH_AREA,ZIPCODE,POLICEPRECINCT,CITYCOUNCILDISTRICT,COMMUNITYDISTRICT,COMMUNITYSCHOOLDISTRICT,CONGRESSIONALDISTRICT,REOPEN_INDICATOR,SPECIAL_EVENT_INDICATOR,STANDBY_INDICATOR,TRANSFER_INDICATOR
207,183654152,12/31/2018 10:57:02 PM,RESPIR,4,RESPIR,4,12/31/2018 10:58:17 PM,Y,75,12/31/2018 10:58:25 PM,12/31/2018 11:07:42 PM,Y,640.0,565.0,NaN,NaN,12/31/2018 11:32:32 PM,N,87.0,BROOKLYN,K7,11221.0,83.0,37.0,304.0,32.0,7.0,N,N,N,N
267,183654085,12/31/2018 10:41:01 PM,UNKNOW,4,UNKNOW,4,12/31/2018 10:42:25 PM,Y,84,12/31/2018 10:43:07 PM,NaN,N,NaN,NaN,NaN,NaN,12/31/2018 10:46:33 PM,N,87.0,MANHATTAN,M3,10022.0,17.0,4.0,106.0,2.0,12.0,N,N,N,N
279,183654073,12/31/2018 10:38:22 PM,UNC,2,UNC,2,12/31/2018 10:38:35 PM,Y,13,12/31/2018 10:38:49 PM,12/31/2018 10:42:57 PM,Y,275.0,262.0,NaN,NaN,12/31/2018 10:55:58 PM,N,87.0,BROOKLYN,K4,11236.0,69.0,46.0,318.0,18.0,8.0,N,N,N,N
323,183654022,12/31/2018 10:25:55 PM,UNKNOW,4,UNKNOW,4,12/31/2018 10:26:10 PM,Y,15,12/31/2018 10:26:22 PM,NaN,N,NaN,NaN,NaN,NaN,12/31/2018 10:31:45 PM,N,87.0,BROOKLYN,K5,11216.0,79.0,36.0,303.0,13.0,8.0,N,N,N,N
349,183653988,12/31/2018 10:17:05 PM,DRUG,4,DRUG,4,12/31/2018 10:17:21 PM,Y,16,12/31/2018 10:17:30 PM,NaN,N,NaN,NaN,NaN,NaN,12/31/2018 10:18:10 PM,N,87.0,BROOKLYN,K7,11211.0,90.0,34.0,301.0,14.0,7.0,N,N,N,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
52393,130010100,01/01/2013 12:24:24 AM,UNC,2,UNC,2,01/01/2013 12:26:04 AM,Y,100,01/01/2013 12:26:33 AM,01/01/2013 12:33:17 AM,Y,533.0,433.0,NaN,NaN,01/01/2013 12:48:42 AM,N,87.0,MANHATTAN,M2,10010.0,13.0,4.0,106.0,2.0,12.0,N,N,N,N
52411,130010081,01/01/2013 12:20:12 AM,SEIZR,3,SEIZR,3,01/01/2013 12:24:11 AM,Y,239,01/01/2013 12:24:11 AM,01/01/2013 12:26:59 AM,Y,407.0,168.0,NaN,NaN,01/01/2013 12:50:17 AM,Y,87.0,MANHATTAN,M3,10036.0,14.0,3.0,104.0,2.0,10.0,N,N,N,N
52433,130010057,01/01/2013 12:14:43 AM,ABDPN,5,ABDPN,5,01/01/2013 12:31:49 AM,Y,1026,01/01/2013 12:31:49 AM,01/01/2013 01:03:10 AM,Y,2907.0,1881.0,NaN,NaN,01/01/2013 01:16:44 AM,Y,87.0,MANHATTAN,M3,10019.0,18.0,3.0,104.0,2.0,10.0,N,N,N,N
52448,130010039,01/01/2013 12:09:57 AM,UNKNOW,4,UNKNOW,4,01/01/2013 12:10:13 AM,Y,16,01/01/2013 12:10:25 AM,01/01/2013 12:23:28 AM,Y,811.0,795.0,NaN,NaN,01/01/2013 12:26:22 AM,N,87.0,RICHMOND / STATEN ISLAND,S1,10303.0,121.0,49.0,501.0,31.0,11.0,N,N,N,N
52471,130010014,01/01/2013 12:03:41 AM,MCI21P,2,MCI21P,2,01/01/2013 12:03:53 AM,Y,12,01/01/2013 12:04:06 AM,01/01/2013 12:08:38 AM,Y,297.0,285.0,NaN,NaN,01/01/2013 12:20:20 AM,N,87.0,BROOKLYN,K3,11203.0,67.0,45.0,317.0,18.0,9.0,N,N,N,N

In [19]:
df_87 = df[(df['INCIDENT_DISPOSITION_CODE'] == 87)].compute()

In [22]:
df.groupby('ZIPCODE').count().compute()

,CAD_INCIDENT_ID,INCIDENT_DATETIME,INITIAL_CALL_TYPE,INITIAL_SEVERITY_LEVEL_CODE,FINAL_CALL_TYPE,FINAL_SEVERITY_LEVEL_CODE,FIRST_ASSIGNMENT_DATETIME,VALID_DISPATCH_RSPNS_TIME_INDC,DISPATCH_RESPONSE_SECONDS_QY,FIRST_ACTIVATION_DATETIME,FIRST_ON_SCENE_DATETIME,VALID_INCIDENT_RSPNS_TIME_INDC,INCIDENT_RESPONSE_SECONDS_QY,INCIDENT_TRAVEL_TM_SECONDS_QY,FIRST_TO_HOSP_DATETIME,FIRST_HOSP_ARRIVAL_DATETIME,INCIDENT_CLOSE_DATETIME,HELD_INDICATOR,INCIDENT_DISPOSITION_CODE,BOROUGH,INCIDENT_DISPATCH_AREA,POLICEPRECINCT,CITYCOUNCILDISTRICT,COMMUNITYDISTRICT,COMMUNITYSCHOOLDISTRICT,CONGRESSIONALDISTRICT,REOPEN_INDICATOR,SPECIAL_EVENT_INDICATOR,STANDBY_INDICATOR,TRANSFER_INDICATOR
ZIPCODE,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
10000.0,927,927,927,927,927,927,912,927,927,910,854,927,853,854,444,431,927,927,912,927,927,927,927,927,927,927,927,927,927,927
10001.0,101271,101271,101271,101271,101271,101271,100475,101271,101271,100274,97207,101271,97202,97207,64917,64410,101236,101271,100306,101271,101271,101271,101271,101271,101271,101271,101271,101271,101271,101271
10002.0,100970,100970,100970,100970,100970,100970,100322,100970,100970,100147,97804,100970,97797,97801,70033,69673,100935,100970,100208,100970,100970,100970,100970,100970,100625,100970,100970,100970,100970,100970
10003.0,87305,87305,87305,87305,87305,87305,86534,87305,87305,86319,84018,87305,84007,84013,54699,54370,87274,87305,86407,87305,87305,87305,87305,87305,87305,87305,87305,87305,87305,87305
10004.0,13278,13278,13278,13278,13278,13278,13155,13278,13278,13109,12692,13278,12687,12692,8860,8825,13275,13278,13138,13278,13278,13278,13278,13278,13278,13278,13278,13278,13278,13278
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10167.0,34,34,34,34,34,34,34,34,34,34,33,34,33,33,25,25,34,34,34,34,34,34,34,34,34,34,34,34,34,34
10176.0,25,25,25,25,25,25,25,25,25,24,24,25,24,24,16,16,25,25,24,25,25,25,25,25,25,25,25,25,25,25
83.0,22,22,22,22,22,22,22,22,22,22,20,22,20,20,9,9,22,22,22,22,22,22,22,22,22,22,22,22,22,22
12345.0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1
10175.0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1

In [20]:
df_87.groupby('ZIPCODE').count()

,CAD_INCIDENT_ID,INCIDENT_DATETIME,INITIAL_CALL_TYPE,INITIAL_SEVERITY_LEVEL_CODE,FINAL_CALL_TYPE,FINAL_SEVERITY_LEVEL_CODE,FIRST_ASSIGNMENT_DATETIME,VALID_DISPATCH_RSPNS_TIME_INDC,DISPATCH_RESPONSE_SECONDS_QY,FIRST_ACTIVATION_DATETIME,FIRST_ON_SCENE_DATETIME,VALID_INCIDENT_RSPNS_TIME_INDC,INCIDENT_RESPONSE_SECONDS_QY,INCIDENT_TRAVEL_TM_SECONDS_QY,FIRST_TO_HOSP_DATETIME,FIRST_HOSP_ARRIVAL_DATETIME,INCIDENT_CLOSE_DATETIME,HELD_INDICATOR,INCIDENT_DISPOSITION_CODE,BOROUGH,INCIDENT_DISPATCH_AREA,POLICEPRECINCT,CITYCOUNCILDISTRICT,COMMUNITYDISTRICT,COMMUNITYSCHOOLDISTRICT,CONGRESSIONALDISTRICT,REOPEN_INDICATOR,SPECIAL_EVENT_INDICATOR,STANDBY_INDICATOR,TRANSFER_INDICATOR
ZIPCODE,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
83.0,5,5,5,5,5,5,5,5,5,5,4,5,4,4,0,0,5,5,5,5,5,5,5,5,5,5,5,5,5,5
10000.0,125,125,125,125,125,125,125,125,125,123,87,125,87,87,0,0,125,125,125,125,125,125,125,125,125,125,125,125,125,125
10001.0,4181,4181,4181,4181,4181,4181,4181,4181,4181,4110,2556,4181,2553,2556,13,7,4181,4181,4181,4181,4181,4181,4181,4181,4181,4181,4181,4181,4181,4181
10002.0,2497,2497,2497,2497,2497,2497,2497,2497,2497,2424,1347,2497,1346,1347,5,5,2496,2497,2497,2497,2497,2497,2497,2497,2460,2497,2497,2497,2497,2497
10003.0,2879,2879,2879,2879,2879,2879,2879,2879,2879,2798,1692,2879,1690,1692,10,3,2877,2879,2879,2879,2879,2879,2879,2879,2879,2879,2879,2879,2879,2879
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11692.0,429,429,429,429,429,429,429,429,429,414,267,429,266,267,1,0,429,429,429,429,429,429,429,429,429,429,429,429,429,429
11693.0,560,560,560,560,560,560,560,560,560,554,369,560,368,369,1,0,560,560,560,560,560,560,560,560,558,560,560,560,560,560
11694.0,577,577,577,577,577,577,577,577,577,562,397,577,395,397,0,0,577,577,577,577,577,577,577,577,577,577,577,577,577,577
11695.0,22,22,22,22,22,22,22,22,22,22,17,22,17,17,0,0,22,22,22,22,22,22,22,22,22,22,22,22,22,22
11697.0,513,513,513,513,513,513,513,513,513,509,382,513,382,382,0,0,513,513,513,513,513,513,513,513,513,513,513,513,513,513

In [23]:
df.tail()

,CAD_INCIDENT_ID,INCIDENT_DATETIME,INITIAL_CALL_TYPE,INITIAL_SEVERITY_LEVEL_CODE,FINAL_CALL_TYPE,FINAL_SEVERITY_LEVEL_CODE,FIRST_ASSIGNMENT_DATETIME,VALID_DISPATCH_RSPNS_TIME_INDC,DISPATCH_RESPONSE_SECONDS_QY,FIRST_ACTIVATION_DATETIME,FIRST_ON_SCENE_DATETIME,VALID_INCIDENT_RSPNS_TIME_INDC,INCIDENT_RESPONSE_SECONDS_QY,INCIDENT_TRAVEL_TM_SECONDS_QY,FIRST_TO_HOSP_DATETIME,FIRST_HOSP_ARRIVAL_DATETIME,INCIDENT_CLOSE_DATETIME,HELD_INDICATOR,INCIDENT_DISPOSITION_CODE,BOROUGH,INCIDENT_DISPATCH_AREA,ZIPCODE,POLICEPRECINCT,CITYCOUNCILDISTRICT,COMMUNITYDISTRICT,COMMUNITYSCHOOLDISTRICT,CONGRESSIONALDISTRICT,REOPEN_INDICATOR,SPECIAL_EVENT_INDICATOR,STANDBY_INDICATOR,TRANSFER_INDICATOR
52479,130010006,01/01/2013 12:01:26 AM,INJURY,5,INJURY,5,01/01/2013 12:01:58 AM,Y,32,01/01/2013 12:02:55 AM,01/01/2013 12:15:42 AM,Y,856.0,824.0,01/01/2013 12:27:42 AM,01/01/2013 12:31:13 AM,01/01/2013 12:53:12 AM,N,82.0,BRONX,B2,10457.0,48.0,15.0,206.0,10.0,15.0,N,N,N,N
52480,130010005,01/01/2013 12:01:16 AM,SICK,6,SICK,6,01/01/2013 12:02:12 AM,Y,56,01/01/2013 12:02:55 AM,01/01/2013 12:15:04 AM,Y,828.0,772.0,01/01/2013 12:34:54 AM,01/01/2013 12:53:02 AM,01/01/2013 01:20:28 AM,N,82.0,BRONX,B2,10453.0,46.0,14.0,205.0,10.0,15.0,N,N,N,N
52481,130010004,01/01/2013 12:01:04 AM,ARREST,1,ARREST,1,01/01/2013 12:01:33 AM,Y,29,01/01/2013 12:01:58 AM,01/01/2013 12:08:13 AM,Y,429.0,400.0,NaN,NaN,01/01/2013 12:38:05 AM,N,83.0,QUEENS,Q3,11418.0,102.0,29.0,409.0,27.0,5.0,N,N,N,N
52482,130010002,01/01/2013 12:00:19 AM,CARD,3,CARD,3,01/01/2013 12:01:18 AM,Y,59,01/01/2013 12:02:08 AM,01/01/2013 12:14:30 AM,Y,851.0,792.0,NaN,NaN,01/01/2013 12:55:34 AM,N,93.0,BRONX,B1,10454.0,40.0,8.0,201.0,7.0,15.0,N,N,N,N
52483,130010001,01/01/2013 12:00:04 AM,RESPIR,4,RESPIR,4,01/01/2013 12:01:45 AM,Y,101,01/01/2013 12:01:51 AM,01/01/2013 12:13:21 AM,Y,797.0,696.0,01/01/2013 12:28:49 AM,01/01/2013 12:38:15 AM,01/01/2013 01:04:56 AM,N,82.0,BRONX,B3,10472.0,43.0,18.0,209.0,12.0,15.0,N,N,N,N

In [ ]:
df.get_partition(0).compute()

### Identify calls/year in dask dataframe

In [25]:
# of calls in 2013 = 1_314_692
df[(df['CAD_INCIDENT_ID'] > 130000000) & (df['CAD_INCIDENT_ID'] < 140000000)].compute()

,CAD_INCIDENT_ID,INCIDENT_DATETIME,INITIAL_CALL_TYPE,INITIAL_SEVERITY_LEVEL_CODE,FINAL_CALL_TYPE,FINAL_SEVERITY_LEVEL_CODE,FIRST_ASSIGNMENT_DATETIME,VALID_DISPATCH_RSPNS_TIME_INDC,DISPATCH_RESPONSE_SECONDS_QY,FIRST_ACTIVATION_DATETIME,FIRST_ON_SCENE_DATETIME,VALID_INCIDENT_RSPNS_TIME_INDC,INCIDENT_RESPONSE_SECONDS_QY,INCIDENT_TRAVEL_TM_SECONDS_QY,FIRST_TO_HOSP_DATETIME,FIRST_HOSP_ARRIVAL_DATETIME,INCIDENT_CLOSE_DATETIME,HELD_INDICATOR,INCIDENT_DISPOSITION_CODE,BOROUGH,INCIDENT_DISPATCH_AREA,ZIPCODE,POLICEPRECINCT,CITYCOUNCILDISTRICT,COMMUNITYDISTRICT,COMMUNITYSCHOOLDISTRICT,CONGRESSIONALDISTRICT,REOPEN_INDICATOR,SPECIAL_EVENT_INDICATOR,STANDBY_INDICATOR,TRANSFER_INDICATOR
108536,133653553,12/31/2013 11:59:50 PM,UNKNOW,4,UNKNOW,4,01/01/2014 12:00:25 AM,Y,35,01/01/2014 12:00:39 AM,01/01/2014 12:14:19 AM,Y,869.0,834.0,NaN,NaN,01/01/2014 12:27:16 AM,N,90.0,BROOKLYN,K4,11208.0,75.0,37.0,305.0,19.0,7.0,N,N,N,N
108537,133653552,12/31/2013 11:59:38 PM,INJURY,5,INJURY,5,01/01/2014 12:00:04 AM,Y,26,01/01/2014 12:00:12 AM,01/01/2014 12:03:47 AM,Y,249.0,223.0,01/01/2014 12:21:13 AM,01/01/2014 12:47:06 AM,01/01/2014 12:47:38 AM,N,82.0,MANHATTAN,M2,10010.0,13.0,3.0,105.0,2.0,12.0,N,N,N,N
108538,133653551,12/31/2013 11:58:22 PM,DIFFBR,2,DIFFBR,2,12/31/2013 11:58:42 PM,Y,20,12/31/2013 11:58:50 PM,01/01/2014 12:02:29 AM,Y,247.0,227.0,01/01/2014 12:23:10 AM,01/01/2014 12:32:45 AM,01/01/2014 12:48:10 AM,N,82.0,BROOKLYN,K7,11249.0,90.0,33.0,301.0,14.0,7.0,N,N,N,N
108539,133653550,12/31/2013 11:57:52 PM,SICK,6,SICK,6,12/31/2013 11:58:45 PM,Y,53,12/31/2013 11:58:58 PM,01/01/2014 12:05:46 AM,Y,474.0,421.0,NaN,NaN,01/01/2014 12:30:41 AM,N,93.0,QUEENS,Q3,11416.0,102.0,32.0,409.0,27.0,7.0,N,N,N,N
108540,133653549,12/31/2013 11:57:40 PM,SHOT,3,SHOT,3,12/31/2013 11:58:11 PM,Y,31,12/31/2013 11:58:20 PM,01/01/2014 12:03:04 AM,Y,324.0,293.0,NaN,NaN,01/01/2014 12:19:43 AM,N,90.0,QUEENS,Q2,11413.0,105.0,31.0,413.0,29.0,5.0,N,N,N,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
52479,130010006,01/01/2013 12:01:26 AM,INJURY,5,INJURY,5,01/01/2013 12:01:58 AM,Y,32,01/01/2013 12:02:55 AM,01/01/2013 12:15:42 AM,Y,856.0,824.0,01/01/2013 12:27:42 AM,01/01/2013 12:31:13 AM,01/01/2013 12:53:12 AM,N,82.0,BRONX,B2,10457.0,48.0,15.0,206.0,10.0,15.0,N,N,N,N
52480,130010005,01/01/2013 12:01:16 AM,SICK,6,SICK,6,01/01/2013 12:02:12 AM,Y,56,01/01/2013 12:02:55 AM,01/01/2013 12:15:04 AM,Y,828.0,772.0,01/01/2013 12:34:54 AM,01/01/2013 12:53:02 AM,01/01/2013 01:20:28 AM,N,82.0,BRONX,B2,10453.0,46.0,14.0,205.0,10.0,15.0,N,N,N,N
52481,130010004,01/01/2013 12:01:04 AM,ARREST,1,ARREST,1,01/01/2013 12:01:33 AM,Y,29,01/01/2013 12:01:58 AM,01/01/2013 12:08:13 AM,Y,429.0,400.0,NaN,NaN,01/01/2013 12:38:05 AM,N,83.0,QUEENS,Q3,11418.0,102.0,29.0,409.0,27.0,5.0,N,N,N,N
52482,130010002,01/01/2013 12:00:19 AM,CARD,3,CARD,3,01/01/2013 12:01:18 AM,Y,59,01/01/2013 12:02:08 AM,01/01/2013 12:14:30 AM,Y,851.0,792.0,NaN,NaN,01/01/2013 12:55:34 AM,N,93.0,BRONX,B1,10454.0,40.0,8.0,201.0,7.0,15.0,N,N,N,N
52483,130010001,01/01/2013 12:00:04 AM,RESPIR,4,RESPIR,4,01/01/2013 12:01:45 AM,Y,101,01/01/2013 12:01:51 AM,01/01/2013 12:13:21 AM,Y,797.0,696.0,01/01/2013 12:28:49 AM,01/01/2013 12:38:15 AM,01/01/2013 01:04:56 AM,N,82.0,BRONX,B3,10472.0,43.0,18.0,209.0,12.0,15.0,N,N,N,N

In [26]:
# of calls in 2014 = 1_357_418
df[(df['CAD_INCIDENT_ID'] > 140000000) & (df['CAD_INCIDENT_ID'] < 150000000)].compute()

,CAD_INCIDENT_ID,INCIDENT_DATETIME,INITIAL_CALL_TYPE,INITIAL_SEVERITY_LEVEL_CODE,FINAL_CALL_TYPE,FINAL_SEVERITY_LEVEL_CODE,FIRST_ASSIGNMENT_DATETIME,VALID_DISPATCH_RSPNS_TIME_INDC,DISPATCH_RESPONSE_SECONDS_QY,FIRST_ACTIVATION_DATETIME,FIRST_ON_SCENE_DATETIME,VALID_INCIDENT_RSPNS_TIME_INDC,INCIDENT_RESPONSE_SECONDS_QY,INCIDENT_TRAVEL_TM_SECONDS_QY,FIRST_TO_HOSP_DATETIME,FIRST_HOSP_ARRIVAL_DATETIME,INCIDENT_CLOSE_DATETIME,HELD_INDICATOR,INCIDENT_DISPOSITION_CODE,BOROUGH,INCIDENT_DISPATCH_AREA,ZIPCODE,POLICEPRECINCT,CITYCOUNCILDISTRICT,COMMUNITYDISTRICT,COMMUNITYSCHOOLDISTRICT,CONGRESSIONALDISTRICT,REOPEN_INDICATOR,SPECIAL_EVENT_INDICATOR,STANDBY_INDICATOR,TRANSFER_INDICATOR
122235,143653765,12/31/2014 11:58:55 PM,ABDPN,5,ABDPN,5,12/31/2014 11:59:45 PM,Y,50,01/01/2015 12:00:02 AM,01/01/2015 12:09:45 AM,Y,650.0,600.0,01/01/2015 12:24:20 AM,01/01/2015 12:34:41 AM,01/01/2015 01:03:41 AM,N,82.0,BROOKLYN,K4,11236.0,69.0,42.0,318.0,18.0,8.0,N,N,N,N
122236,143653764,12/31/2014 11:58:51 PM,INJURY,5,INJURY,5,01/01/2015 12:25:30 AM,Y,1599,01/01/2015 12:25:30 AM,NaN,N,NaN,NaN,NaN,NaN,01/01/2015 12:42:53 AM,Y,90.0,MANHATTAN,M3,10019.0,18.0,4.0,105.0,2.0,12.0,N,N,N,N
122237,143653763,12/31/2014 11:58:50 PM,UNC,2,UNC,2,01/01/2015 12:01:20 AM,Y,150,01/01/2015 12:01:36 AM,01/01/2015 12:04:07 AM,Y,317.0,167.0,01/01/2015 12:22:42 AM,01/01/2015 12:31:06 AM,01/01/2015 01:00:22 AM,N,82.0,MANHATTAN,M2,10011.0,10.0,3.0,104.0,2.0,10.0,N,N,N,N
122238,143653762,12/31/2014 11:58:22 PM,INJURY,5,INJURY,5,12/31/2014 11:59:15 PM,Y,53,12/31/2014 11:59:27 PM,01/01/2015 12:04:27 AM,Y,365.0,312.0,NaN,NaN,01/01/2015 12:17:14 AM,N,96.0,MANHATTAN,M1,NaN,NaN,NaN,NaN,NaN,NaN,N,N,N,N
122239,143653761,12/31/2014 11:58:18 PM,INJURY,4,INJURY,4,12/31/2014 11:58:54 PM,Y,36,12/31/2014 11:59:00 PM,01/01/2015 12:05:33 AM,Y,435.0,399.0,01/01/2015 12:16:47 AM,01/01/2015 12:25:42 AM,01/01/2015 12:39:59 AM,N,82.0,BROOKLYN,K2,11218.0,70.0,44.0,314.0,20.0,10.0,N,N,N,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
108531,140010005,01/01/2014 12:01:47 AM,ABDPN,5,RESPIR,4,01/01/2014 12:19:28 AM,Y,1061,01/01/2014 12:19:34 AM,01/01/2014 12:27:21 AM,Y,1534.0,473.0,NaN,NaN,01/01/2014 12:28:28 AM,Y,87.0,BRONX,B4,10467.0,49.0,15.0,211.0,11.0,14.0,N,N,N,N
108532,140010004,01/01/2014 12:01:07 AM,OTHER,6,OTHER,6,01/01/2014 12:02:44 AM,Y,97,01/01/2014 12:04:23 AM,01/01/2014 12:13:34 AM,Y,747.0,650.0,01/01/2014 12:37:18 AM,01/01/2014 12:45:42 AM,01/01/2014 01:25:57 AM,N,82.0,BRONX,B4,10467.0,49.0,15.0,211.0,11.0,14.0,N,N,N,N
108533,140010003,01/01/2014 12:01:00 AM,SICK,6,SICK,6,01/01/2014 12:01:11 AM,Y,11,01/01/2014 12:01:44 AM,01/01/2014 12:10:07 AM,Y,547.0,536.0,01/01/2014 12:26:31 AM,01/01/2014 12:49:11 AM,01/01/2014 01:20:30 AM,N,82.0,BROOKLYN,K4,11207.0,75.0,42.0,305.0,19.0,8.0,N,N,N,N
108534,140010002,01/01/2014 12:00:39 AM,SICPED,4,SICPED,4,01/01/2014 12:01:58 AM,Y,79,01/01/2014 12:02:12 AM,01/01/2014 12:05:44 AM,Y,305.0,226.0,NaN,NaN,01/01/2014 12:59:35 AM,N,93.0,BRONX,B3,10473.0,43.0,18.0,209.0,8.0,15.0,N,N,N,N
108535,140010001,01/01/2014 12:00:07 AM,UNC,2,UNC,2,01/01/2014 12:00:54 AM,Y,47,01/01/2014 12:01:02 AM,01/01/2014 12:03:37 AM,Y,210.0,163.0,01/01/2014 12:23:18 AM,01/01/2014 12:55:41 AM,01/01/2014 01:02:01 AM,N,82.0,BRONX,B3,10475.0,45.0,12.0,210.0,11.0,16.0,N,N,N,N

In [27]:
# of calls in 2015 = 1_440_113
df[(df['CAD_INCIDENT_ID'] > 150000000) & (df['CAD_INCIDENT_ID'] < 160000000)].compute()

,CAD_INCIDENT_ID,INCIDENT_DATETIME,INITIAL_CALL_TYPE,INITIAL_SEVERITY_LEVEL_CODE,FINAL_CALL_TYPE,FINAL_SEVERITY_LEVEL_CODE,FIRST_ASSIGNMENT_DATETIME,VALID_DISPATCH_RSPNS_TIME_INDC,DISPATCH_RESPONSE_SECONDS_QY,FIRST_ACTIVATION_DATETIME,FIRST_ON_SCENE_DATETIME,VALID_INCIDENT_RSPNS_TIME_INDC,INCIDENT_RESPONSE_SECONDS_QY,INCIDENT_TRAVEL_TM_SECONDS_QY,FIRST_TO_HOSP_DATETIME,FIRST_HOSP_ARRIVAL_DATETIME,INCIDENT_CLOSE_DATETIME,HELD_INDICATOR,INCIDENT_DISPOSITION_CODE,BOROUGH,INCIDENT_DISPATCH_AREA,ZIPCODE,POLICEPRECINCT,CITYCOUNCILDISTRICT,COMMUNITYDISTRICT,COMMUNITYSCHOOLDISTRICT,CONGRESSIONALDISTRICT,REOPEN_INDICATOR,SPECIAL_EVENT_INDICATOR,STANDBY_INDICATOR,TRANSFER_INDICATOR
55856,153653771,12/31/2015 11:59:54 PM,INJURY,5,INJURY,5,01/01/2016 12:11:06 AM,Y,672,01/01/2016 12:11:34 AM,01/01/2016 12:14:58 AM,Y,904.0,232.0,NaN,NaN,01/01/2016 12:40:19 AM,Y,93.0,BROOKLYN,K1,11229.0,61.0,48.0,315.0,21.0,11.0,N,N,N,N
55857,153653770,12/31/2015 11:59:40 PM,DRUG,4,DRUG,4,01/01/2016 12:13:33 AM,Y,833,01/01/2016 12:13:37 AM,01/01/2016 12:31:05 AM,Y,1885.0,1052.0,01/01/2016 12:55:28 AM,01/01/2016 01:20:53 AM,01/01/2016 01:46:21 AM,Y,82.0,MANHATTAN,X1,10018.0,14.0,3.0,105.0,2.0,12.0,N,N,N,N
55858,153653769,12/31/2015 11:59:28 PM,UNC,2,UNC,2,12/31/2015 11:59:28 PM,Y,0,12/31/2015 11:59:28 PM,12/31/2015 11:59:28 PM,Y,0.0,0.0,01/01/2016 12:20:37 AM,01/01/2016 12:34:17 AM,01/01/2016 01:13:08 AM,N,82.0,BROOKLYN,K1,11224.0,60.0,47.0,313.0,21.0,8.0,N,N,N,N
55859,153653767,12/31/2015 11:59:07 PM,DRUG,4,DRUG,4,12/31/2015 11:59:07 PM,Y,0,12/31/2015 11:59:07 PM,12/31/2015 11:59:07 PM,Y,0.0,0.0,NaN,NaN,01/01/2016 12:09:07 AM,N,90.0,MANHATTAN,M3,10001.0,14.0,3.0,105.0,2.0,12.0,N,N,N,N
55860,153653766,12/31/2015 11:58:56 PM,INJMAJ,3,INJMAJ,3,01/01/2016 12:00:59 AM,Y,123,01/01/2016 12:01:30 AM,01/01/2016 12:09:45 AM,Y,649.0,526.0,01/01/2016 12:33:10 AM,01/01/2016 12:43:39 AM,01/01/2016 01:13:01 AM,N,82.0,QUEENS,Q6,11369.0,115.0,21.0,403.0,30.0,14.0,N,N,N,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
122230,150010005,01/01/2015 12:01:38 AM,INBLED,3,INBLED,3,01/01/2015 12:01:49 AM,Y,11,01/01/2015 12:02:07 AM,01/01/2015 12:06:44 AM,Y,306.0,295.0,01/01/2015 12:24:06 AM,01/01/2015 12:27:38 AM,01/01/2015 12:54:11 AM,N,82.0,BROOKLYN,K4,11234.0,63.0,46.0,318.0,22.0,8.0,N,N,N,N
122231,150010004,01/01/2015 12:01:21 AM,INJURY,5,INJURY,5,01/01/2015 12:01:50 AM,Y,29,01/01/2015 12:03:02 AM,01/01/2015 12:08:43 AM,Y,442.0,413.0,NaN,NaN,01/01/2015 12:23:57 AM,N,90.0,BRONX,B2,10451.0,44.0,8.0,204.0,7.0,15.0,N,N,N,N
122232,150010003,01/01/2015 12:01:14 AM,DIFFBR,2,DIFFBR,2,01/01/2015 12:01:40 AM,Y,26,01/01/2015 12:02:02 AM,01/01/2015 12:09:21 AM,Y,487.0,461.0,01/01/2015 12:31:38 AM,01/01/2015 12:46:21 AM,01/01/2015 01:16:53 AM,N,82.0,BRONX,B3,10472.0,43.0,18.0,209.0,8.0,15.0,N,N,N,N
122233,150010002,01/01/2015 12:00:48 AM,SICKFC,6,SICKFC,6,01/01/2015 12:01:32 AM,Y,44,01/01/2015 12:03:34 AM,01/01/2015 12:11:34 AM,Y,646.0,602.0,01/01/2015 12:19:42 AM,01/01/2015 12:25:47 AM,01/01/2015 12:54:05 AM,N,82.0,BRONX,B2,10457.0,48.0,17.0,206.0,12.0,15.0,N,N,N,N
122234,150010001,01/01/2015 12:00:44 AM,EDP,7,EDP,7,01/01/2015 12:01:54 AM,Y,70,01/01/2015 12:02:00 AM,01/01/2015 12:14:47 AM,Y,843.0,773.0,01/01/2015 12:25:30 AM,01/01/2015 12:39:21 AM,01/01/2015 01:04:50 AM,N,82.0,MANHATTAN,M3,10001.0,14.0,3.0,105.0,2.0,12.0,N,N,N,N

In [28]:
# of calls in 2016 = 1_444_137
df[(df['CAD_INCIDENT_ID'] > 160000000) & (df['CAD_INCIDENT_ID'] < 170000000)].compute()

,CAD_INCIDENT_ID,INCIDENT_DATETIME,INITIAL_CALL_TYPE,INITIAL_SEVERITY_LEVEL_CODE,FINAL_CALL_TYPE,FINAL_SEVERITY_LEVEL_CODE,FIRST_ASSIGNMENT_DATETIME,VALID_DISPATCH_RSPNS_TIME_INDC,DISPATCH_RESPONSE_SECONDS_QY,FIRST_ACTIVATION_DATETIME,FIRST_ON_SCENE_DATETIME,VALID_INCIDENT_RSPNS_TIME_INDC,INCIDENT_RESPONSE_SECONDS_QY,INCIDENT_TRAVEL_TM_SECONDS_QY,FIRST_TO_HOSP_DATETIME,FIRST_HOSP_ARRIVAL_DATETIME,INCIDENT_CLOSE_DATETIME,HELD_INDICATOR,INCIDENT_DISPOSITION_CODE,BOROUGH,INCIDENT_DISPATCH_AREA,ZIPCODE,POLICEPRECINCT,CITYCOUNCILDISTRICT,COMMUNITYDISTRICT,COMMUNITYSCHOOLDISTRICT,CONGRESSIONALDISTRICT,REOPEN_INDICATOR,SPECIAL_EVENT_INDICATOR,STANDBY_INDICATOR,TRANSFER_INDICATOR
252764,163664269,12/31/2016 11:59:44 PM,DRUG,4,DRUG,4,12/31/2016 11:59:54 PM,Y,10,01/01/2017 12:01:04 AM,01/01/2017 12:07:54 AM,Y,490.0,480.0,NaN,NaN,01/01/2017 12:14:56 AM,N,96.0,QUEENS,Q1,11691.0,101.0,31.0,414.0,27.0,5.0,N,N,N,N
252765,163664268,12/31/2016 11:59:15 PM,MVAINJ,4,MVAINJ,4,01/01/2017 12:00:36 AM,Y,81,01/01/2017 12:01:22 AM,01/01/2017 12:20:07 AM,Y,1252.0,1171.0,NaN,NaN,01/01/2017 12:54:27 AM,N,93.0,BROOKLYN,K4,11234.0,63.0,46.0,318.0,22.0,8.0,N,N,N,N
252766,163664267,12/31/2016 11:59:09 PM,SICK,6,SICK,6,12/31/2016 11:59:23 PM,Y,14,12/31/2016 11:59:37 PM,01/01/2017 12:06:42 AM,Y,453.0,439.0,01/01/2017 12:23:18 AM,01/01/2017 12:35:58 AM,01/01/2017 12:54:46 AM,N,82.0,MANHATTAN,M8,10039.0,32.0,9.0,110.0,5.0,13.0,N,N,N,N
252767,163664266,12/31/2016 11:58:30 PM,INJURY,5,INJURY,5,12/31/2016 11:58:44 PM,Y,14,12/31/2016 11:58:50 PM,01/01/2017 12:15:37 AM,Y,1027.0,1013.0,01/01/2017 12:49:11 AM,01/01/2017 12:56:44 AM,01/01/2017 02:42:17 AM,N,82.0,MANHATTAN,M7,10027.0,28.0,9.0,110.0,5.0,13.0,N,N,N,N
252768,163664265,12/31/2016 11:57:36 PM,STNDBY,8,STNDBY,8,NaN,N,0,NaN,NaN,N,NaN,NaN,NaN,NaN,12/31/2016 11:57:36 PM,N,NaN,BROOKLYN,K1,NaN,NaN,NaN,NaN,NaN,NaN,N,N,Y,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55851,160010007,01/01/2016 12:02:18 AM,INJURY,5,INJURY,5,01/01/2016 12:02:56 AM,Y,38,01/01/2016 12:03:04 AM,01/01/2016 12:06:00 AM,Y,222.0,184.0,01/01/2016 12:34:12 AM,01/01/2016 12:44:51 AM,01/01/2016 01:21:13 AM,N,82.0,BRONX,B2,10456.0,44.0,8.0,204.0,9.0,15.0,N,N,N,N
55852,160010005,01/01/2016 12:01:32 AM,SICK,6,SICK,6,01/01/2016 12:02:11 AM,Y,39,01/01/2016 12:02:21 AM,01/01/2016 12:10:31 AM,Y,539.0,500.0,01/01/2016 12:35:50 AM,01/01/2016 12:42:02 AM,01/01/2016 12:59:16 AM,N,82.0,QUEENS,Q4,11374.0,112.0,29.0,406.0,28.0,6.0,N,N,N,N
55853,160010004,01/01/2016 12:01:28 AM,UNC,2,UNC,2,01/01/2016 12:02:21 AM,Y,53,01/01/2016 12:03:09 AM,01/01/2016 12:14:03 AM,Y,755.0,702.0,01/01/2016 12:28:37 AM,01/01/2016 12:31:48 AM,01/01/2016 01:03:18 AM,N,82.0,MANHATTAN,M1,10002.0,7.0,1.0,103.0,1.0,7.0,N,N,N,N
55854,160010002,01/01/2016 12:00:18 AM,SICK,6,SICK,6,01/01/2016 12:01:29 AM,Y,71,01/01/2016 12:01:42 AM,01/01/2016 12:04:09 AM,Y,231.0,160.0,01/01/2016 12:50:43 AM,01/01/2016 01:02:32 AM,01/01/2016 01:39:03 AM,N,82.0,BRONX,B4,10469.0,47.0,12.0,212.0,11.0,16.0,N,N,N,N
55855,160010001,01/01/2016 12:00:17 AM,OTHER,6,OTHER,6,NaN,N,0,NaN,NaN,N,NaN,NaN,NaN,NaN,01/01/2016 12:00:17 AM,N,NaN,BROOKLYN,K6,11201.0,84.0,33.0,302.0,13.0,8.0,N,N,N,N

In [6]:
# of calls in 2017 = 1_466_865
df[(df['CAD_INCIDENT_ID'] > 170000000) & (df['CAD_INCIDENT_ID'] < 180000000)].compute()

,CAD_INCIDENT_ID,INCIDENT_DATETIME,INITIAL_CALL_TYPE,INITIAL_SEVERITY_LEVEL_CODE,FINAL_CALL_TYPE,FINAL_SEVERITY_LEVEL_CODE,FIRST_ASSIGNMENT_DATETIME,VALID_DISPATCH_RSPNS_TIME_INDC,DISPATCH_RESPONSE_SECONDS_QY,FIRST_ACTIVATION_DATETIME,FIRST_ON_SCENE_DATETIME,VALID_INCIDENT_RSPNS_TIME_INDC,INCIDENT_RESPONSE_SECONDS_QY,INCIDENT_TRAVEL_TM_SECONDS_QY,FIRST_TO_HOSP_DATETIME,FIRST_HOSP_ARRIVAL_DATETIME,INCIDENT_CLOSE_DATETIME,HELD_INDICATOR,INCIDENT_DISPOSITION_CODE,BOROUGH,INCIDENT_DISPATCH_AREA,ZIPCODE,POLICEPRECINCT,CITYCOUNCILDISTRICT,COMMUNITYDISTRICT,COMMUNITYSCHOOLDISTRICT,CONGRESSIONALDISTRICT,REOPEN_INDICATOR,SPECIAL_EVENT_INDICATOR,STANDBY_INDICATOR,TRANSFER_INDICATOR
158318,173654111,12/31/2017 11:59:45 PM,INJMAJ,3,INJMAJ,3,12/31/2017 11:59:51 PM,Y,6,01/01/2018 12:00:04 AM,01/01/2018 12:07:04 AM,Y,439.0,433.0,01/01/2018 12:24:05 AM,01/01/2018 12:35:20 AM,01/01/2018 01:01:53 AM,N,82.0,QUEENS,Q3,11420.0,106.0,28.0,410.0,27.0,5.0,N,N,N,N
158319,173654110,12/31/2017 11:59:41 PM,EDP,7,EDP,7,01/01/2018 12:01:17 AM,Y,96,01/01/2018 12:02:11 AM,01/01/2018 12:23:49 AM,Y,1448.0,1352.0,NaN,NaN,01/01/2018 01:11:38 AM,N,90.0,BROOKLYN,K5,11213.0,77.0,41.0,308.0,17.0,9.0,N,N,N,N
158320,173654109,12/31/2017 11:59:13 PM,SHOT,3,SHOT,3,01/01/2018 12:00:45 AM,Y,92,01/01/2018 12:01:32 AM,01/01/2018 12:04:10 AM,Y,297.0,205.0,NaN,NaN,01/01/2018 12:06:53 AM,N,90.0,MANHATTAN,M3,10017.0,17.0,4.0,106.0,2.0,12.0,N,N,N,N
158321,173654107,12/31/2017 11:59:03 PM,UNC,2,UNC,2,12/31/2017 11:59:17 PM,Y,14,12/31/2017 11:59:27 PM,01/01/2018 12:09:26 AM,Y,623.0,609.0,01/01/2018 12:29:50 AM,01/01/2018 12:37:14 AM,01/01/2018 01:09:31 AM,N,82.0,BRONX,B4,10467.0,49.0,15.0,211.0,11.0,14.0,N,N,N,N
158322,173654106,12/31/2017 11:58:42 PM,ABDPN,5,ABDPN,5,12/31/2017 11:58:51 PM,Y,9,01/01/2018 12:00:49 AM,01/01/2018 12:09:13 AM,Y,631.0,622.0,NaN,NaN,01/01/2018 12:36:02 AM,N,93.0,BROOKLYN,K7,11237.0,90.0,34.0,301.0,32.0,7.0,N,N,N,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
252759,170010005,01/01/2017 12:02:01 AM,UNC,2,UNC,2,01/01/2017 12:02:33 AM,Y,32,01/01/2017 12:02:39 AM,01/01/2017 12:09:41 AM,Y,460.0,428.0,NaN,NaN,01/01/2017 01:27:39 AM,N,93.0,QUEENS,Q2,11436.0,113.0,28.0,412.0,27.0,5.0,N,N,N,N
252760,170010004,01/01/2017 12:01:27 AM,DRUG,4,DRUG,4,01/01/2017 12:01:42 AM,Y,15,01/01/2017 12:03:17 AM,01/01/2017 12:03:54 AM,Y,147.0,132.0,NaN,NaN,01/01/2017 12:10:03 AM,N,90.0,MANHATTAN,M1,10002.0,7.0,1.0,103.0,1.0,7.0,N,N,N,N
252761,170010003,01/01/2017 12:01:13 AM,OTHER,6,OTHER,6,01/01/2017 12:02:56 AM,Y,103,01/01/2017 12:03:06 AM,01/01/2017 12:12:29 AM,Y,676.0,573.0,NaN,NaN,01/01/2017 12:15:56 AM,N,90.0,MANHATTAN,M2,10001.0,13.0,3.0,105.0,2.0,12.0,N,N,N,N
252762,170010002,01/01/2017 12:01:09 AM,STNDBY,8,STNDBY,8,01/01/2017 10:14:55 AM,N,0,01/01/2017 10:15:02 AM,01/01/2017 10:47:31 AM,N,NaN,1956.0,NaN,NaN,01/01/2017 01:48:12 PM,N,87.0,BROOKLYN,K1,NaN,NaN,NaN,NaN,NaN,NaN,Y,N,Y,N
252763,170010001,01/01/2017 12:01:03 AM,CARD,3,CARD,3,01/01/2017 12:02:01 AM,Y,58,01/01/2017 12:03:19 AM,01/01/2017 12:06:24 AM,Y,321.0,263.0,NaN,NaN,01/01/2017 12:09:35 AM,N,90.0,BROOKLYN,K7,11221.0,83.0,34.0,304.0,32.0,7.0,N,N,N,N

In [5]:
# of calls in 2018 = 1_534_623
df[(df['CAD_INCIDENT_ID'] > 180000000) & (df['CAD_INCIDENT_ID'] < 190000000)].compute()

,CAD_INCIDENT_ID,INCIDENT_DATETIME,INITIAL_CALL_TYPE,INITIAL_SEVERITY_LEVEL_CODE,FINAL_CALL_TYPE,FINAL_SEVERITY_LEVEL_CODE,FIRST_ASSIGNMENT_DATETIME,VALID_DISPATCH_RSPNS_TIME_INDC,DISPATCH_RESPONSE_SECONDS_QY,FIRST_ACTIVATION_DATETIME,FIRST_ON_SCENE_DATETIME,VALID_INCIDENT_RSPNS_TIME_INDC,INCIDENT_RESPONSE_SECONDS_QY,INCIDENT_TRAVEL_TM_SECONDS_QY,FIRST_TO_HOSP_DATETIME,FIRST_HOSP_ARRIVAL_DATETIME,INCIDENT_CLOSE_DATETIME,HELD_INDICATOR,INCIDENT_DISPOSITION_CODE,BOROUGH,INCIDENT_DISPATCH_AREA,ZIPCODE,POLICEPRECINCT,CITYCOUNCILDISTRICT,COMMUNITYDISTRICT,COMMUNITYSCHOOLDISTRICT,CONGRESSIONALDISTRICT,REOPEN_INDICATOR,SPECIAL_EVENT_INDICATOR,STANDBY_INDICATOR,TRANSFER_INDICATOR
0,183654386,12/31/2018 11:59:46 PM,CARDBR,2,CARDBR,2,12/31/2018 11:59:54 PM,Y,8,01/01/2019 12:00:51 AM,01/01/2019 12:07:27 AM,Y,461.0,453.0,01/01/2019 12:15:08 AM,01/01/2019 12:21:51 AM,01/01/2019 01:00:20 AM,N,82.0,BROOKLYN,K6,11201.0,84.0,35.0,302.0,13.0,8.0,N,N,N,N
1,183654385,12/31/2018 11:59:20 PM,MVAINJ,4,MVAINJ,4,01/01/2019 12:01:10 AM,Y,110,01/01/2019 12:02:25 AM,01/01/2019 12:07:19 AM,Y,479.0,369.0,NaN,NaN,01/01/2019 12:19:49 AM,N,91.0,QUEENS,Q3,11416.0,102.0,32.0,409.0,27.0,7.0,N,N,N,N
2,183654384,12/31/2018 11:58:45 PM,SICK,6,SICK,6,01/01/2019 12:00:43 AM,Y,118,01/01/2019 12:02:08 AM,01/01/2019 12:14:18 AM,Y,933.0,815.0,01/01/2019 12:23:59 AM,01/01/2019 12:34:07 AM,01/01/2019 01:21:30 AM,N,82.0,QUEENS,Q6,11369.0,115.0,21.0,480.0,30.0,14.0,N,N,N,N
3,183654383,12/31/2018 11:58:14 PM,INJMAJ,3,INJMAJ,3,12/31/2018 11:58:22 PM,Y,8,12/31/2018 11:58:37 PM,01/01/2019 12:04:10 AM,Y,356.0,348.0,01/01/2019 01:06:29 AM,01/01/2019 01:15:30 AM,01/01/2019 02:02:12 AM,N,82.0,BROOKLYN,K1,11214.0,62.0,47.0,311.0,20.0,11.0,N,N,N,N
4,183654382,12/31/2018 11:57:42 PM,UNC,2,UNC,2,01/01/2019 12:00:39 AM,Y,177,01/01/2019 12:01:03 AM,01/01/2019 12:15:00 AM,Y,1038.0,861.0,01/01/2019 01:18:22 AM,01/01/2019 01:22:01 AM,01/01/2019 02:34:19 AM,N,82.0,MANHATTAN,M3,10019.0,18.0,4.0,105.0,2.0,12.0,N,N,N,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
158313,180010005,01/01/2018 12:01:14 AM,UNKNOW,4,UNKNOW,4,01/01/2018 12:01:24 AM,Y,10,01/01/2018 12:01:48 AM,01/01/2018 12:07:47 AM,Y,393.0,383.0,NaN,NaN,01/01/2018 12:20:26 AM,N,90.0,BROOKLYN,K6,11238.0,88.0,35.0,302.0,13.0,8.0,N,N,N,N
158314,180010004,01/01/2018 12:00:58 AM,UNC,2,UNC,2,01/01/2018 12:01:08 AM,Y,10,01/01/2018 12:01:24 AM,01/01/2018 12:13:06 AM,Y,728.0,718.0,01/01/2018 12:36:04 AM,01/01/2018 12:42:42 AM,01/01/2018 01:31:15 AM,N,82.0,BRONX,B1,10454.0,40.0,8.0,201.0,7.0,15.0,N,N,N,N
158315,180010003,01/01/2018 12:00:52 AM,INJURY,5,INJURY,5,01/01/2018 12:01:36 AM,Y,44,01/01/2018 12:01:45 AM,01/01/2018 12:10:14 AM,Y,562.0,518.0,NaN,NaN,01/01/2018 12:12:32 AM,N,96.0,BRONX,B3,10465.0,45.0,13.0,210.0,8.0,14.0,N,N,N,N
158316,180010002,01/01/2018 12:00:50 AM,SICK,6,SICK,6,01/01/2018 12:01:20 AM,Y,30,01/01/2018 12:01:39 AM,01/01/2018 12:03:55 AM,Y,185.0,155.0,01/01/2018 12:18:30 AM,01/01/2018 12:25:41 AM,01/01/2018 01:04:55 AM,N,82.0,BROOKLYN,K2,11232.0,72.0,38.0,307.0,15.0,7.0,N,N,N,N
158317,180010001,01/01/2018 12:00:47 AM,TRAUMA,2,TRAUMA,2,01/01/2018 12:01:22 AM,Y,35,01/01/2018 12:01:33 AM,01/01/2018 12:02:23 AM,Y,96.0,61.0,01/01/2018 12:13:53 AM,01/01/2018 12:18:13 AM,01/01/2018 01:02:09 AM,N,82.0,BRONX,B3,NaN,NaN,NaN,NaN,NaN,NaN,N,N,N,N

In [8]:
df.head()

,CAD_INCIDENT_ID,INCIDENT_DATETIME,INITIAL_CALL_TYPE,INITIAL_SEVERITY_LEVEL_CODE,FINAL_CALL_TYPE,FINAL_SEVERITY_LEVEL_CODE,FIRST_ASSIGNMENT_DATETIME,VALID_DISPATCH_RSPNS_TIME_INDC,DISPATCH_RESPONSE_SECONDS_QY,FIRST_ACTIVATION_DATETIME,FIRST_ON_SCENE_DATETIME,VALID_INCIDENT_RSPNS_TIME_INDC,INCIDENT_RESPONSE_SECONDS_QY,INCIDENT_TRAVEL_TM_SECONDS_QY,FIRST_TO_HOSP_DATETIME,FIRST_HOSP_ARRIVAL_DATETIME,INCIDENT_CLOSE_DATETIME,HELD_INDICATOR,INCIDENT_DISPOSITION_CODE,BOROUGH,INCIDENT_DISPATCH_AREA,ZIPCODE,POLICEPRECINCT,CITYCOUNCILDISTRICT,COMMUNITYDISTRICT,COMMUNITYSCHOOLDISTRICT,CONGRESSIONALDISTRICT,REOPEN_INDICATOR,SPECIAL_EVENT_INDICATOR,STANDBY_INDICATOR,TRANSFER_INDICATOR
0,183654386,12/31/2018 11:59:46 PM,CARDBR,2,CARDBR,2,12/31/2018 11:59:54 PM,Y,8,01/01/2019 12:00:51 AM,01/01/2019 12:07:27 AM,Y,461.0,453.0,01/01/2019 12:15:08 AM,01/01/2019 12:21:51 AM,01/01/2019 01:00:20 AM,N,82.0,BROOKLYN,K6,11201.0,84.0,35.0,302.0,13.0,8.0,N,N,N,N
1,183654385,12/31/2018 11:59:20 PM,MVAINJ,4,MVAINJ,4,01/01/2019 12:01:10 AM,Y,110,01/01/2019 12:02:25 AM,01/01/2019 12:07:19 AM,Y,479.0,369.0,NaN,NaN,01/01/2019 12:19:49 AM,N,91.0,QUEENS,Q3,11416.0,102.0,32.0,409.0,27.0,7.0,N,N,N,N
2,183654384,12/31/2018 11:58:45 PM,SICK,6,SICK,6,01/01/2019 12:00:43 AM,Y,118,01/01/2019 12:02:08 AM,01/01/2019 12:14:18 AM,Y,933.0,815.0,01/01/2019 12:23:59 AM,01/01/2019 12:34:07 AM,01/01/2019 01:21:30 AM,N,82.0,QUEENS,Q6,11369.0,115.0,21.0,480.0,30.0,14.0,N,N,N,N
3,183654383,12/31/2018 11:58:14 PM,INJMAJ,3,INJMAJ,3,12/31/2018 11:58:22 PM,Y,8,12/31/2018 11:58:37 PM,01/01/2019 12:04:10 AM,Y,356.0,348.0,01/01/2019 01:06:29 AM,01/01/2019 01:15:30 AM,01/01/2019 02:02:12 AM,N,82.0,BROOKLYN,K1,11214.0,62.0,47.0,311.0,20.0,11.0,N,N,N,N
4,183654382,12/31/2018 11:57:42 PM,UNC,2,UNC,2,01/01/2019 12:00:39 AM,Y,177,01/01/2019 12:01:03 AM,01/01/2019 12:15:00 AM,Y,1038.0,861.0,01/01/2019 01:18:22 AM,01/01/2019 01:22:01 AM,01/01/2019 02:34:19 AM,N,82.0,MANHATTAN,M3,10019.0,18.0,4.0,105.0,2.0,12.0,N,N,N,N

In [7]:
df.dtypes

CAD_INCIDENT_ID                     int64
INCIDENT_DATETIME                  object
INITIAL_CALL_TYPE                  object
INITIAL_SEVERITY_LEVEL_CODE         int64
FINAL_CALL_TYPE                    object
FINAL_SEVERITY_LEVEL_CODE           int64
FIRST_ASSIGNMENT_DATETIME          object
VALID_DISPATCH_RSPNS_TIME_INDC     object
DISPATCH_RESPONSE_SECONDS_QY        int64
FIRST_ACTIVATION_DATETIME          object
FIRST_ON_SCENE_DATETIME            object
VALID_INCIDENT_RSPNS_TIME_INDC     object
INCIDENT_RESPONSE_SECONDS_QY      float64
INCIDENT_TRAVEL_TM_SECONDS_QY     float64
FIRST_TO_HOSP_DATETIME             object
FIRST_HOSP_ARRIVAL_DATETIME        object
INCIDENT_CLOSE_DATETIME            object
HELD_INDICATOR                     object
INCIDENT_DISPOSITION_CODE         float64
BOROUGH                            object
INCIDENT_DISPATCH_AREA             object
ZIPCODE                           float64
POLICEPRECINCT                    float64
CITYCOUNCILDISTRICT               float64
COMMUNITYDISTRICT                 float64
COMMUNITYSCHOOLDISTRICT           float64
CONGRESSIONALDISTRICT             float64
REOPEN_INDICATOR                   object
SPECIAL_EVENT_INDICATOR            object
STANDBY_INDICATOR                  object
TRANSFER_INDICATOR                 object
dtype: object

In [14]:
df.isna().sum().compute()

CAD_INCIDENT_ID                         0
INCIDENT_DATETIME                       0
INITIAL_CALL_TYPE                       0
INITIAL_SEVERITY_LEVEL_CODE             0
FINAL_CALL_TYPE                         0
FINAL_SEVERITY_LEVEL_CODE               0
FIRST_ASSIGNMENT_DATETIME           59065
VALID_DISPATCH_RSPNS_TIME_INDC          0
DISPATCH_RESPONSE_SECONDS_QY            0
FIRST_ACTIVATION_DATETIME           74260
FIRST_ON_SCENE_DATETIME            273186
VALID_INCIDENT_RSPNS_TIME_INDC          0
INCIDENT_RESPONSE_SECONDS_QY       274572
INCIDENT_TRAVEL_TM_SECONDS_QY      273313
FIRST_TO_HOSP_DATETIME            2526241
FIRST_HOSP_ARRIVAL_DATETIME       2567274
INCIDENT_CLOSE_DATETIME              3227
HELD_INDICATOR                          0
INCIDENT_DISPOSITION_CODE           69852
BOROUGH                                 0
INCIDENT_DISPATCH_AREA                  0
ZIPCODE                            164396
POLICEPRECINCT                     164086
CITYCOUNCILDISTRICT                167234
COMMUNITYDISTRICT                  164092
COMMUNITYSCHOOLDISTRICT            168424
CONGRESSIONALDISTRICT              167234
REOPEN_INDICATOR                        0
SPECIAL_EVENT_INDICATOR                 0
STANDBY_INDICATOR                       0
TRANSFER_INDICATOR                      0
dtype: int64

In [17]:
# Is COMMUNITYSCHOOLDISTRICT mostly NaN in the same places as ZIPCODE? 
df[df['COMMUNITYSCHOOLDISTRICT'].isna() & df['ZIPCODE'].notnull()].compute()

,CAD_INCIDENT_ID,INCIDENT_DATETIME,INITIAL_CALL_TYPE,INITIAL_SEVERITY_LEVEL_CODE,FINAL_CALL_TYPE,FINAL_SEVERITY_LEVEL_CODE,FIRST_ASSIGNMENT_DATETIME,VALID_DISPATCH_RSPNS_TIME_INDC,DISPATCH_RESPONSE_SECONDS_QY,FIRST_ACTIVATION_DATETIME,FIRST_ON_SCENE_DATETIME,VALID_INCIDENT_RSPNS_TIME_INDC,INCIDENT_RESPONSE_SECONDS_QY,INCIDENT_TRAVEL_TM_SECONDS_QY,FIRST_TO_HOSP_DATETIME,FIRST_HOSP_ARRIVAL_DATETIME,INCIDENT_CLOSE_DATETIME,HELD_INDICATOR,INCIDENT_DISPOSITION_CODE,BOROUGH,INCIDENT_DISPATCH_AREA,ZIPCODE,POLICEPRECINCT,CITYCOUNCILDISTRICT,COMMUNITYDISTRICT,COMMUNITYSCHOOLDISTRICT,CONGRESSIONALDISTRICT,REOPEN_INDICATOR,SPECIAL_EVENT_INDICATOR,STANDBY_INDICATOR,TRANSFER_INDICATOR
324,183654021,12/31/2018 10:25:40 PM,MVAINJ,4,MVAINJ,4,12/31/2018 10:26:02 PM,Y,22,12/31/2018 10:26:11 PM,12/31/2018 10:31:13 PM,Y,333.0,311.0,12/31/2018 11:05:09 PM,12/31/2018 11:25:35 PM,12/31/2018 11:47:15 PM,N,82.0,RICHMOND / STATEN ISLAND,S1,10305.0,122.0,50.0,502.0,NaN,11.0,N,N,N,N
2005,183652111,12/31/2018 01:52:09 PM,MVAINJ,4,MVAINJ,4,12/31/2018 01:53:24 PM,Y,75,12/31/2018 01:53:34 PM,12/31/2018 01:54:20 PM,Y,131.0,56.0,12/31/2018 02:21:44 PM,12/31/2018 02:31:40 PM,12/31/2018 02:51:14 PM,N,82.0,BRONX,B3,10464.0,45.0,13.0,210.0,NaN,14.0,N,N,N,N
2226,183651863,12/31/2018 12:49:01 PM,EDP,7,EDP,7,12/31/2018 12:49:18 PM,Y,17,12/31/2018 12:49:31 PM,12/31/2018 12:55:30 PM,Y,389.0,372.0,NaN,NaN,12/31/2018 01:01:42 PM,N,90.0,QUEENS,Q1,11693.0,100.0,32.0,484.0,NaN,5.0,N,N,N,N
6958,183640948,12/30/2018 06:12:52 AM,MVAINJ,4,MVAINJ,4,12/30/2018 06:13:26 AM,Y,34,12/30/2018 06:13:31 AM,12/30/2018 06:30:23 AM,Y,1051.0,1017.0,NaN,NaN,12/30/2018 06:39:35 AM,N,91.0,MANHATTAN,Q6,10017.0,19.0,5.0,106.0,NaN,12.0,N,N,N,N
9328,183632735,12/29/2018 04:29:32 PM,ALTMEN,3,ALTMEN,3,12/29/2018 04:29:56 PM,Y,24,12/29/2018 04:31:16 PM,12/29/2018 04:40:39 PM,Y,667.0,643.0,NaN,NaN,12/29/2018 05:59:29 PM,N,90.0,MANHATTAN,M1,10038.0,5.0,1.0,101.0,NaN,10.0,N,N,N,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6870,130122373,01/12/2013 03:31:12 PM,MVAINJ,4,MVAINJ,4,01/12/2013 03:31:57 PM,Y,45,01/12/2013 03:32:14 PM,01/12/2013 03:49:04 PM,Y,1072.0,1027.0,NaN,NaN,01/12/2013 04:38:24 PM,N,93.0,QUEENS,Q7,11357.0,109.0,19.0,407.0,NaN,14.0,N,N,N,N
12756,130110410,01/11/2013 03:41:13 AM,INJURY,4,INJURY,4,01/11/2013 03:42:48 AM,Y,95,01/11/2013 03:42:58 AM,01/11/2013 03:53:45 AM,Y,752.0,657.0,01/11/2013 04:10:53 AM,01/11/2013 04:18:22 AM,01/11/2013 04:50:58 AM,N,82.0,QUEENS,Q7,11357.0,109.0,19.0,407.0,NaN,14.0,N,N,N,N
15266,130102066,01/10/2013 01:27:00 PM,ASTHMB,2,ASTHMB,2,01/10/2013 01:28:44 PM,Y,104,01/10/2013 01:29:16 PM,01/10/2013 01:40:16 PM,Y,796.0,692.0,01/10/2013 02:03:10 PM,01/10/2013 02:10:57 PM,01/10/2013 02:52:10 PM,Y,82.0,QUEENS,Q7,11357.0,109.0,19.0,407.0,NaN,14.0,N,N,N,N
35400,130050542,01/05/2013 04:14:00 AM,EDP,7,EDP,7,01/05/2013 04:14:28 AM,Y,28,01/05/2013 04:15:00 AM,NaN,N,NaN,NaN,NaN,NaN,01/05/2013 04:23:11 AM,N,87.0,MANHATTAN,M1,10002.0,7.0,2.0,103.0,NaN,7.0,N,N,N,N
44939,130022854,01/02/2013 05:30:17 PM,MVAINJ,4,MVAINJ,4,01/02/2013 05:30:25 PM,Y,8,01/02/2013 05:31:12 PM,01/02/2013 05:37:57 PM,Y,460.0,452.0,01/02/2013 05:57:49 PM,01/02/2013 06:08:47 PM,01/02/2013 06:50:09 PM,N,82.0,QUEENS,Q7,11357.0,109.0,19.0,407.0,NaN,14.0,N,N,N,N

In [15]:
# Save df without null zipcodes, we shall focus on it for now
df_nnz = df[df['ZIPCODE'].notnull()].compute()

In [16]:
df_nnz.shape

(8393452, 31)

In [28]:
df.describe()

Dask DataFrame Structure:
              CAD_INCIDENT_ID INITIAL_SEVERITY_LEVEL_CODE FINAL_SEVERITY_LEVEL_CODE DISPATCH_RESPONSE_SECONDS_QY INCIDENT_RESPONSE_SECONDS_QY INCIDENT_TRAVEL_TM_SECONDS_QY INCIDENT_DISPOSITION_CODE  ZIPCODE POLICEPRECINCT CITYCOUNCILDISTRICT COMMUNITYDISTRICT COMMUNITYSCHOOLDISTRICT CONGRESSIONALDISTRICT
npartitions=1
                      float64                     float64                   float64                      float64                      float64                       float64                   float64  float64        float64             float64           float64                 float64               float64
                          ...                         ...                       ...                          ...                          ...                           ...                       ...      ...            ...                 ...               ...                     ...                   ...
Dask Name: describe-numeric, 1633 tasks

In [29]:
df_nnz.describe()

,CAD_INCIDENT_ID,INITIAL_SEVERITY_LEVEL_CODE,FINAL_SEVERITY_LEVEL_CODE,DISPATCH_RESPONSE_SECONDS_QY,INCIDENT_RESPONSE_SECONDS_QY,INCIDENT_TRAVEL_TM_SECONDS_QY,INCIDENT_DISPOSITION_CODE,ZIPCODE,POLICEPRECINCT,CITYCOUNCILDISTRICT,COMMUNITYDISTRICT,COMMUNITYSCHOOLDISTRICT,CONGRESSIONALDISTRICT
count,8.393452e+06,8.393452e+06,8.393452e+06,8.393452e+06,8.129902e+06,8.130747e+06,8.326788e+06,8.393452e+06,8.393452e+06,8.390304e+06,8.393446e+06,8.389174e+06,8.390304e+06
mean,1.577615e+08,4.277647e+00,4.171309e+00,9.012347e+01,5.625278e+02,4.739410e+02,8.470451e+01,1.073609e+04,6.159525e+01,2.303025e+01,2.610733e+02,1.471577e+01,1.063481e+01
std,1.706924e+07,1.694110e+00,1.703804e+00,5.053302e+02,6.476521e+02,3.698684e+02,4.545528e+00,5.496244e+02,3.409373e+01,1.498261e+01,1.178344e+02,9.594900e+00,3.336008e+00
min,1.300100e+08,1.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,8.200000e+01,8.300000e+01,1.000000e+00,1.000000e+00,1.010000e+02,1.000000e+00,3.000000e+00
25%,1.422612e+08,3.000000e+00,3.000000e+00,1.400000e+01,3.090000e+02,2.790000e+02,8.200000e+01,1.012800e+04,3.400000e+01,9.000000e+00,1.120000e+02,6.000000e+00,8.000000e+00
50%,1.605126e+08,4.000000e+00,4.000000e+00,2.300000e+01,4.360000e+02,3.990000e+02,8.200000e+01,1.047200e+04,6.000000e+01,2.000000e+01,3.010000e+02,1.300000e+01,1.100000e+01
75%,1.721912e+08,6.000000e+00,6.000000e+00,4.300000e+01,6.250000e+02,5.680000e+02,8.700000e+01,1.122600e+04,8.800000e+01,3.600000e+01,3.170000e+02,2.300000e+01,1.300000e+01
max,1.836544e+08,9.000000e+00,8.000000e+00,3.232700e+04,3.237500e+04,9.539000e+04,9.600000e+01,1.234500e+04,1.230000e+02,5.100000e+01,5.950000e+02,3.200000e+01,1.600000e+01

In [36]:
df_nnz.shape

(8393452, 31)

In [24]:
df_nnz['INCIDENT_DISPOSITION_CODE'].isnull().sum()

66664

In [31]:
df_nnz[df_nnz['INCIDENT_DISPOSITION_CODE'].isnull()]

,CAD_INCIDENT_ID,INCIDENT_DATETIME,INITIAL_CALL_TYPE,INITIAL_SEVERITY_LEVEL_CODE,FINAL_CALL_TYPE,FINAL_SEVERITY_LEVEL_CODE,FIRST_ASSIGNMENT_DATETIME,VALID_DISPATCH_RSPNS_TIME_INDC,DISPATCH_RESPONSE_SECONDS_QY,FIRST_ACTIVATION_DATETIME,FIRST_ON_SCENE_DATETIME,VALID_INCIDENT_RSPNS_TIME_INDC,INCIDENT_RESPONSE_SECONDS_QY,INCIDENT_TRAVEL_TM_SECONDS_QY,FIRST_TO_HOSP_DATETIME,FIRST_HOSP_ARRIVAL_DATETIME,INCIDENT_CLOSE_DATETIME,HELD_INDICATOR,INCIDENT_DISPOSITION_CODE,BOROUGH,INCIDENT_DISPATCH_AREA,ZIPCODE,POLICEPRECINCT,CITYCOUNCILDISTRICT,COMMUNITYDISTRICT,COMMUNITYSCHOOLDISTRICT,CONGRESSIONALDISTRICT,REOPEN_INDICATOR,SPECIAL_EVENT_INDICATOR,STANDBY_INDICATOR,TRANSFER_INDICATOR
94,183654276,12/31/2018 11:31:55 PM,UNKNOW,4,UNKNOW,4,NaN,N,0,NaN,NaN,N,NaN,NaN,NaN,NaN,12/31/2018 11:34:03 PM,N,NaN,RICHMOND / STATEN ISLAND,S1,10310.0,120.0,49.0,501.0,31.0,11.0,N,N,N,N
194,183654167,12/31/2018 11:00:43 PM,OTHER,6,OTHER,6,NaN,N,0,NaN,NaN,N,NaN,NaN,NaN,NaN,12/31/2018 11:13:16 PM,Y,NaN,BROOKLYN,K4,11207.0,75.0,42.0,305.0,19.0,8.0,N,N,N,N
299,183654050,12/31/2018 10:33:43 PM,OTHER,6,OTHER,6,NaN,N,0,NaN,NaN,N,NaN,NaN,NaN,NaN,12/31/2018 10:33:43 PM,N,NaN,BRONX,B3,10462.0,43.0,18.0,209.0,11.0,14.0,N,N,N,N
364,183653969,12/31/2018 10:12:43 PM,SHOT,3,SHOT,3,NaN,N,0,NaN,NaN,N,NaN,NaN,NaN,NaN,12/31/2018 10:14:39 PM,N,NaN,BRONX,B4,10466.0,47.0,12.0,212.0,11.0,16.0,N,N,N,N
531,183653775,12/31/2018 09:22:44 PM,OTHER,6,OTHER,6,NaN,N,0,NaN,NaN,N,NaN,NaN,NaN,NaN,12/31/2018 09:22:44 PM,N,NaN,MANHATTAN,M7,10027.0,28.0,9.0,110.0,5.0,13.0,N,N,N,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
52319,130010179,01/01/2013 12:36:50 AM,INJURY,5,INJURY,5,01/01/2013 01:06:39 AM,Y,1789,01/01/2013 01:06:58 AM,NaN,N,NaN,NaN,NaN,NaN,01/01/2013 02:00:40 AM,N,NaN,MANHATTAN,M2,10012.0,6.0,1.0,102.0,2.0,10.0,N,N,N,N
52341,130010157,01/01/2013 12:34:05 AM,OTHER,6,OTHER,6,NaN,N,0,NaN,NaN,N,NaN,NaN,NaN,NaN,01/01/2013 03:43:05 AM,N,NaN,MANHATTAN,M2,10002.0,13.0,4.0,106.0,2.0,12.0,N,N,N,N
52400,130010092,01/01/2013 12:22:02 AM,EDP,7,EDP,7,NaN,N,0,NaN,NaN,N,NaN,NaN,NaN,NaN,01/01/2013 01:30:05 AM,Y,NaN,MANHATTAN,M2,10009.0,9.0,2.0,103.0,1.0,7.0,N,N,N,N
52429,130010061,01/01/2013 12:16:33 AM,EDP,7,EDP,7,NaN,N,0,NaN,NaN,N,NaN,NaN,NaN,NaN,01/01/2013 01:30:36 AM,N,NaN,MANHATTAN,M2,10001.0,13.0,3.0,104.0,2.0,12.0,N,N,N,N
52430,130010060,01/01/2013 12:15:13 AM,EDP,7,EDP,7,NaN,N,0,NaN,NaN,N,NaN,NaN,NaN,NaN,01/01/2013 01:23:23 AM,Y,NaN,MANHATTAN,M7,10035.0,25.0,8.0,111.0,4.0,13.0,N,N,N,N

In [37]:
df_nnz = df_nnz[df_nnz['INCIDENT_DISPOSITION_CODE'].notnull()]

In [42]:
df_nnz['INCIDENT_DISPOSITION_CODE'].unique()

array([82., 91., 93., 90., 96., 87., 83., 94., 95., 92.])

In [47]:
df_nnz['INCIDENT_DISPOSITION_CODE'].value_counts(normalize = True)

82.0    0.715337
93.0    0.113937
90.0    0.086717
96.0    0.034950
87.0    0.030111
91.0    0.011069
83.0    0.006967
94.0    0.000808
95.0    0.000097
92.0    0.000007
Name: INCIDENT_DISPOSITION_CODE, dtype: float64

In [54]:
df_nnz.groupby(['ZIPCODE', 'INCIDENT_DISPOSITION_CODE']).count()

                                   CAD_INCIDENT_ID  INCIDENT_DATETIME  \
ZIPCODE INCIDENT_DISPOSITION_CODE
83.0    82.0                                     9                  9
        87.0                                     5                  5
        90.0                                     6                  6
        93.0                                     1                  1
        96.0                                     1                  1
...                                            ...                ...
11697.0 93.0                                   160                160
        94.0                                    36                 36
        95.0                                     1                  1
        96.0                                    76                 76
12345.0 96.0                                     1                  1

                                   INITIAL_CALL_TYPE  \
ZIPCODE INCIDENT_DISPOSITION_CODE
83.0    82.0                                       9
        87.0                                       5
        90.0                                       6
        93.0                                       1
        96.0                                       1
...                                              ...
11697.0 93.0                                     160
        94.0                                      36
        95.0                                       1
        96.0                                      76
12345.0 96.0                                       1

                                   INITIAL_SEVERITY_LEVEL_CODE  \
ZIPCODE INCIDENT_DISPOSITION_CODE
83.0    82.0                                                 9
        87.0                                                 5
        90.0                                                 6
        93.0                                                 1
        96.0                                                 1
...                                                        ...
11697.0 93.0                                               160
        94.0                                                36
        95.0                                                 1
        96.0                                                76
12345.0 96.0                                                 1

                                   FINAL_CALL_TYPE  FINAL_SEVERITY_LEVEL_CODE  \
ZIPCODE INCIDENT_DISPOSITION_CODE
83.0    82.0                                     9                          9
        87.0                                     5                          5
        90.0                                     6                          6
        93.0                                     1                          1
        96.0                                     1                          1
...                                            ...                        ...
11697.0 93.0                                   160                        160
        94.0                                    36                         36
        95.0                                     1                          1
        96.0                                    76                         76
12345.0 96.0                                     1                          1

                                   FIRST_ASSIGNMENT_DATETIME  \
ZIPCODE INCIDENT_DISPOSITION_CODE
83.0    82.0                                               9
        87.0                                               5
        90.0                                               6
        93.0                                               1
        96.0                                               1
...                                                      ...
11697.0 93.0                                             160
        94.0                                              36
        95.0                                               1
        96.0                                              76
12345.0 96.0                                               1

                                   VALID_DISPATCH_RSPNS_TIME_INDC  \
ZIPCODE INCIDENT_DISPOSITION_CODE
83.0    82.0                                                    9
        87.0                                                    5
        90.0                                                    6
        93.0                                                    1
        96.0                                                    1
...                                                           ...
11697.0 93.0                                                  160
        94.0                                                   36
        95.0                                                    1
        96.0                                                   76
12345.0 96.0                                                    1

                                   DISPATCH_RESPONSE_SECONDS_QY  \
ZIPCODE INCIDENT_DISPOSITION_CODE
83.0    82.0                                                  9
        87.0                                                  5
        90.0                                                  6
        93.0                                                  1
        96.0                                                  1
...                                                         ...
11697.0 93.0                                                160
        94.0                                                 36
        95.0                                                  1
        96.0                                                 76
12345.0 96.0                                                  1

                                   FIRST_ACTIVATION_DATETIME  \
ZIPCODE INCIDENT_DISPOSITION_CODE
83.0    82.0                                               9
        87.0                                               5
        90.0                                               6
        93.0                                               1
        96.0                                               1
...                                                      ...
11697.0 93.0                                             160
        94.0                                              36
        95.0                                               1
        96.0                                              76
12345.0 96.0                                               1

                                   FIRST_ON_SCENE_DATETIME  \
ZIPCODE INCIDENT_DISPOSITION_CODE
83.0    82.0                                             8
        87.0                                             4
        90.0                                             6
        93.0                                             1
        96.0                                             1
...                                                    ...
11697.0 93.0                                           156
        94.0                                            35
        95.0                                             1
        96.0                                            68
12345.0 96.0                                             1

                                   VALID_INCIDENT_RSPNS_TIME_INDC  \
ZIPCODE INCIDENT_DISPOSITION_CODE
83.0    82.0                                                    9
        87.0                                                    5
        90.0                                                    6
        93.0                                                    1
        96.0                                                    1
...                                                           ...
11697.0 93.0                                                  160
        94.0                                                   36
        95.0                                                    1
        96.0                                                   76
12345.0 96.0                                                    1

                                   INCIDENT_RESPONSE_SECONDS_QY  \
ZIPCODE INCIDENT_DISPOSITION_CODE
83.0    82.0                                                  8
        87.0                                                  4
        90.0                                                  6
        93.0                                                  1
        96.0                                                  1
...                                                         ...
11697.0 93.0                                                156
        94.0                                                 35
        95.0                                                  1
        96.0                                                 68
12345.0 96.0                                                  1

                                   INCIDENT_TRAVEL_TM_SECONDS_QY  \
ZIPCODE INCIDENT_DISPOSITION_CODE
83.0    82.0                                                   8
        87.0                                                   4
        90.0                                                   6
        93.0                                                   1
        96.0                                                   1
...                                                          ...
11697.0 93.0                                                 156
        94.0                                                  35
        95.0                                                   1
        96.0                                                  68
12345.0 96.0                                                   1

                                   FIRST_TO_HOSP_DATETIME  \
ZIPCODE INCIDENT_DISPOSITION_CODE
83.0    82.0                                            9
        87.0                                            0
        90.0                                            0
        93.0                                            0
        96.0                                            0
...                                                   ...
11697.0 93.0                                            0
        94.0                                            0
        95.0                                            0
        96.0                                            0
12345.0 96.0                                            0

                                   FIRST_HOSP_ARRIVAL_DATETIME  \
ZIPCODE INCIDENT_DISPOSITION_CODE
83.0    82.0                                                 9
        87.0                                                 0
        90.0                                                 0
        93.0                                                 0
        96.0                                                 0
...                                                        ...
11697.0 93.0                                                 0
        94.0                                                 0
        95.0                                                 0
        96.0                                                 0
12345.0 96.0                                                 0

                                   INCIDENT_CLOSE_DATETIME  HELD_INDICATOR  \
ZIPCODE INCIDENT_DISPOSITION_CODE
83.0    82.0                                             9               9
        87.0                                             5               5
        90.0                                             6               6
        93.0                                             1               1
        96.0                                             1               1
...                                                    ...             ...
11697.0 93.0                                           160             160
        94.0                                            36              36
        95.0                                             1               1
        96.0                                            76              76
12345.0 96.0                                             1               1

                                   BOROUGH  INCIDENT_DISPATCH_AREA  \
ZIPCODE INCIDENT_DISPOSITION_CODE
83.0    82.0                             9                       9
        87.0                             5                       5
        90.0                             6                       6
        93.0                             1                       1
        96.0                             1                       1
...                                    ...                     ...
11697.0 93.0                           160                     160
        94.0                            36                      36
        95.0                             1                       1
        96.0                            76                      76
12345.0 96.0                             1                       1

                                   POLICEPRECINCT  CITYCOUNCILDISTRICT  \
ZIPCODE INCIDENT_DISPOSITION_CODE
83.0    82.0                                    9                    9
        87.0                                    5                    5
        90.0                                    6                    6
        93.0                                    1                    1
        96.0                                    1                    1
...                                           ...                  ...
11697.0 93.0                                  160                  160
        94.0                                   36                   36
        95.0                                    1                    1
        96.0                                   76                   76
12345.0 96.0                                    1                    1

                                   COMMUNITYDISTRICT  COMMUNITYSCHOOLDISTRICT  \
ZIPCODE INCIDENT_DISPOSITION_CODE
83.0    82.0                                       9                        9
        87.0                                       5                        5
        90.0                                       6                        6
        93.0                                       1                        1
        96.0                                       1                        1
...                                              ...                      ...
11697.0 93.0                                     160                      160
        94.0                                      36                       36
        95.0                                       1                        1
        96.0                                      76                       76
12345.0 96.0                                       1                        1

                                   CONGRESSIONALDISTRICT  REOPEN_INDICATOR  \
ZIPCODE INCIDENT_DISPOSITION_CODE
83.0    82.0                                           9                 9
        87.0                                           5                 5
        90.0                                           6                 6
        93.0                                           1                 1
        96.0                                           1                 1
...                                                  ...               ...
11697.0 93.0                                         160               160
        94.0                                          36                36
        95.0                                           1                 1
        96.0                                          76                76
12345.0 96.0                                           1                 1

                                   SPECIAL_EVENT_INDICATOR  STANDBY_INDICATOR  \
ZIPCODE INCIDENT_DISPOSITION_CODE
83.0    82.0                                             9                  9
        87.0                                             5                  5
        90.0                                             6                  6
        93.0                                             1                  1
        96.0                                             1                  1
...                                                    ...                ...
11697.0 93.0                                           160                160
        94.0                                            36                 36
        95.0                                             1                  1
        96.0                                            76                 76
12345.0 96.0                                             1                  1

                                   TRANSFER_INDICATOR
ZIPCODE INCIDENT_DISPOSITION_CODE
83.0    82.0                                        9
        87.0                                        5
        90.0                                        6
        93.0                                        1
        96.0                                        1
...                                               ...
11697.0 93.0                                      160
        94.0                                       36
        95.0                                        1
        96.0                                       76
12345.0 96.0                                        1

[1911 rows x 29 columns]

In [55]:
df_nnz.dtypes

CAD_INCIDENT_ID                     int64
INCIDENT_DATETIME                  object
INITIAL_CALL_TYPE                  object
INITIAL_SEVERITY_LEVEL_CODE         int64
FINAL_CALL_TYPE                    object
FINAL_SEVERITY_LEVEL_CODE           int64
FIRST_ASSIGNMENT_DATETIME          object
VALID_DISPATCH_RSPNS_TIME_INDC     object
DISPATCH_RESPONSE_SECONDS_QY        int64
FIRST_ACTIVATION_DATETIME          object
FIRST_ON_SCENE_DATETIME            object
VALID_INCIDENT_RSPNS_TIME_INDC     object
INCIDENT_RESPONSE_SECONDS_QY      float64
INCIDENT_TRAVEL_TM_SECONDS_QY     float64
FIRST_TO_HOSP_DATETIME             object
FIRST_HOSP_ARRIVAL_DATETIME        object
INCIDENT_CLOSE_DATETIME            object
HELD_INDICATOR                     object
INCIDENT_DISPOSITION_CODE         float64
BOROUGH                            object
INCIDENT_DISPATCH_AREA             object
ZIPCODE                           float64
POLICEPRECINCT                    float64
CITYCOUNCILDISTRICT               float64
COMMUNITYDISTRICT                 float64
COMMUNITYSCHOOLDISTRICT           float64
CONGRESSIONALDISTRICT             float64
REOPEN_INDICATOR                   object
SPECIAL_EVENT_INDICATOR            object
STANDBY_INDICATOR                  object
TRANSFER_INDICATOR                 object
dtype: object

## Divide dataset by year to reduce size

In [68]:
# 2013
df_nnz13 = df_nnz[(df_nnz['CAD_INCIDENT_ID'] > 130000000) & (df_nnz['CAD_INCIDENT_ID'] < 140000000)]

# 2014
df_nnz14 = df_nnz[(df_nnz['CAD_INCIDENT_ID'] > 140000000) & (df_nnz['CAD_INCIDENT_ID'] < 150000000)]

# 2015
df_nnz15 = df_nnz[(df_nnz['CAD_INCIDENT_ID'] > 150000000) & (df_nnz['CAD_INCIDENT_ID'] < 160000000)]

# 2016
df_nnz16 = df_nnz[(df_nnz['CAD_INCIDENT_ID'] > 160000000) & (df_nnz['CAD_INCIDENT_ID'] < 170000000)]

# 2017
df_nnz17 = df_nnz[(df_nnz['CAD_INCIDENT_ID'] > 170000000) & (df_nnz['CAD_INCIDENT_ID'] < 180000000)]

# 2018
df_nnz18 = df_nnz[(df_nnz['CAD_INCIDENT_ID'] > 180000000) & (df_nnz['CAD_INCIDENT_ID'] < 190000000)]

In [74]:
df_nnz13 = df_nnz[(df_nnz['CAD_INCIDENT_ID'] > 130000000) & (df_nnz['CAD_INCIDENT_ID'] < 140000000)]

In [84]:
df_nnz13['INCIDENT_DATETIME'].apply(pd.to_datetime)

108536   2013-12-31 23:59:50
108537   2013-12-31 23:59:38
108538   2013-12-31 23:58:22
108539   2013-12-31 23:57:52
108540   2013-12-31 23:57:40
                 ...
52479    2013-01-01 00:01:26
52480    2013-01-01 00:01:16
52481    2013-01-01 00:01:04
52482    2013-01-01 00:00:19
52483    2013-01-01 00:00:04
Name: INCIDENT_DATETIME, Length: 1271079, dtype: datetime64[ns]

In [81]:
%%timeit
pd.to_datetime(df_nnz13['INCIDENT_DATETIME'].head(1000))   # 12/31/2018 11:31:55 PM

98.2 ms ± 3.57 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

In [80]:
%%timeit
df_nnz13['INCIDENT_DATETIME'].head(1000).astype('datetime64[ns]')

104 ms ± 11 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

In [73]:
df_years = [df_nnz13, df_nnz14, df_nnz15, df_nnz16, df_nnz17, df_nnz18]
dt_list = ['INCIDENT_DATETIME', 'FIRST_ASSIGNMENT_DATETIME', 'FIRST_ACTIVATION_DATETIME',
          'FIRST_ON_SCENE_DATETIME', 'FIRST_TO_HOSP_DATETIME', 'FIRST_HOSP_ARRIVAL_DATETIME',
          'INCIDENT_CLOSE_DATETIME']

for frame in df_years:
    frame[dt_list] = frame.loc[:, dt_list].astype('datetime64[ns]')

C:\Users\Tilevitz Family\Anaconda3\envs\dsi\lib\site-packages\pandas\core\frame.py:3509: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[k1] = value[k2]

KeyboardInterrupt:

In [88]:
df_nnz13['INCIDENT_DATETIME'] = df_nnz13['INCIDENT_DATETIME'].astype('datetime64[ns]')

C:\Users\Tilevitz Family\Anaconda3\envs\dsi\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [89]:
df_nnz13.dtypes

CAD_INCIDENT_ID                            int64
INCIDENT_DATETIME                 datetime64[ns]
INITIAL_CALL_TYPE                         object
INITIAL_SEVERITY_LEVEL_CODE                int64
FINAL_CALL_TYPE                           object
FINAL_SEVERITY_LEVEL_CODE                  int64
FIRST_ASSIGNMENT_DATETIME                 object
VALID_DISPATCH_RSPNS_TIME_INDC            object
DISPATCH_RESPONSE_SECONDS_QY               int64
FIRST_ACTIVATION_DATETIME                 object
FIRST_ON_SCENE_DATETIME                   object
VALID_INCIDENT_RSPNS_TIME_INDC            object
INCIDENT_RESPONSE_SECONDS_QY             float64
INCIDENT_TRAVEL_TM_SECONDS_QY            float64
FIRST_TO_HOSP_DATETIME                    object
FIRST_HOSP_ARRIVAL_DATETIME               object
INCIDENT_CLOSE_DATETIME                   object
HELD_INDICATOR                            object
INCIDENT_DISPOSITION_CODE                float64
BOROUGH                                   object
INCIDENT_DISPATCH_AREA                    object
ZIPCODE                                  float64
POLICEPRECINCT                           float64
CITYCOUNCILDISTRICT                      float64
COMMUNITYDISTRICT                        float64
COMMUNITYSCHOOLDISTRICT                  float64
CONGRESSIONALDISTRICT                    float64
REOPEN_INDICATOR                          object
SPECIAL_EVENT_INDICATOR                   object
STANDBY_INDICATOR                         object
TRANSFER_INDICATOR                        object
dtype: object

In [94]:
df_nnz13.shape

(1271079, 31)

In [93]:
df_nnz13.INCIDENT_DATETIME.dt.hour >= 19

108536     True
108537     True
108538     True
108539     True
108540     True
          ...
52479     False
52480     False
52481     False
52482     False
52483     False
Name: INCIDENT_DATETIME, Length: 1271079, dtype: bool

In [59]:
df_nnz['INCIDENT_DATETIME'] = df_nnz['INCIDENT_DATETIME'].astype('datetime64[ns]')

KeyboardInterrupt:

In [57]:
pd.to_datetime(df_nnz[['INCIDENT_DATETIME', 'FIRST_ASSIGNMENT_DATETIME']])

ValueError: to assemble mappings requires at least that [year, month, day] be specified: [day,month,year] is missing

In [85]:
df_nnz.head()

,CAD_INCIDENT_ID,INCIDENT_DATETIME,INITIAL_CALL_TYPE,INITIAL_SEVERITY_LEVEL_CODE,FINAL_CALL_TYPE,FINAL_SEVERITY_LEVEL_CODE,FIRST_ASSIGNMENT_DATETIME,VALID_DISPATCH_RSPNS_TIME_INDC,DISPATCH_RESPONSE_SECONDS_QY,FIRST_ACTIVATION_DATETIME,FIRST_ON_SCENE_DATETIME,VALID_INCIDENT_RSPNS_TIME_INDC,INCIDENT_RESPONSE_SECONDS_QY,INCIDENT_TRAVEL_TM_SECONDS_QY,FIRST_TO_HOSP_DATETIME,FIRST_HOSP_ARRIVAL_DATETIME,INCIDENT_CLOSE_DATETIME,HELD_INDICATOR,INCIDENT_DISPOSITION_CODE,BOROUGH,INCIDENT_DISPATCH_AREA,ZIPCODE,POLICEPRECINCT,CITYCOUNCILDISTRICT,COMMUNITYDISTRICT,COMMUNITYSCHOOLDISTRICT,CONGRESSIONALDISTRICT,REOPEN_INDICATOR,SPECIAL_EVENT_INDICATOR,STANDBY_INDICATOR,TRANSFER_INDICATOR
0,183654386,12/31/2018 11:59:46 PM,CARDBR,2,CARDBR,2,12/31/2018 11:59:54 PM,Y,8,01/01/2019 12:00:51 AM,01/01/2019 12:07:27 AM,Y,461.0,453.0,01/01/2019 12:15:08 AM,01/01/2019 12:21:51 AM,01/01/2019 01:00:20 AM,N,82.0,BROOKLYN,K6,11201.0,84.0,35.0,302.0,13.0,8.0,N,N,N,N
1,183654385,12/31/2018 11:59:20 PM,MVAINJ,4,MVAINJ,4,01/01/2019 12:01:10 AM,Y,110,01/01/2019 12:02:25 AM,01/01/2019 12:07:19 AM,Y,479.0,369.0,NaN,NaN,01/01/2019 12:19:49 AM,N,91.0,QUEENS,Q3,11416.0,102.0,32.0,409.0,27.0,7.0,N,N,N,N
2,183654384,12/31/2018 11:58:45 PM,SICK,6,SICK,6,01/01/2019 12:00:43 AM,Y,118,01/01/2019 12:02:08 AM,01/01/2019 12:14:18 AM,Y,933.0,815.0,01/01/2019 12:23:59 AM,01/01/2019 12:34:07 AM,01/01/2019 01:21:30 AM,N,82.0,QUEENS,Q6,11369.0,115.0,21.0,480.0,30.0,14.0,N,N,N,N
3,183654383,12/31/2018 11:58:14 PM,INJMAJ,3,INJMAJ,3,12/31/2018 11:58:22 PM,Y,8,12/31/2018 11:58:37 PM,01/01/2019 12:04:10 AM,Y,356.0,348.0,01/01/2019 01:06:29 AM,01/01/2019 01:15:30 AM,01/01/2019 02:02:12 AM,N,82.0,BROOKLYN,K1,11214.0,62.0,47.0,311.0,20.0,11.0,N,N,N,N
4,183654382,12/31/2018 11:57:42 PM,UNC,2,UNC,2,01/01/2019 12:00:39 AM,Y,177,01/01/2019 12:01:03 AM,01/01/2019 12:15:00 AM,Y,1038.0,861.0,01/01/2019 01:18:22 AM,01/01/2019 01:22:01 AM,01/01/2019 02:34:19 AM,N,82.0,MANHATTAN,M3,10019.0,18.0,4.0,105.0,2.0,12.0,N,N,N,N